        // Introduction To Java Script!

        // JavaScript Case Is Sensitive!

        // JavaScript Left To Right!

        // JavaScript Line By Line!

        // Chapter (1st)!

        // alert ("Learning JavaScript!");
        // window.alert ("Learning JavaScript!");

        // alert ("Welcome To JavaScript...\nPlease Click On OK! ");
        // window.alert ("Welcome To JavaScript\nHello Users!");

        // Chapter No (2nd)!

        // var a = "Hayyan";
        // var b = "Jibran";
        // var c = b+a;
        // alert (c);

        // var a = "JIbran";
        // var b = a+"Hayyan";
        // alert (b);

        // var a = "JIbran";
        // var b = "Hayyan"+a;
        // alert (b);

        // var nationality;
        // nationality = "U.S.";

        // alert(nationality);

        // var a = "Hayyan";
        // var b = "Jibran";
        // var c = a+b;
        // alert (c);

        // Chapter (3rd)!

        // var a = 5;
        // var b = 15;
        // var c = 30; 
        // var d = 5;
        // var e = a+b+c+d;
        // alert (e);

        // var a = 23;
        // var b = a+7;
        // alert(b);

        // var a = 10;
        // var b = 15;
        // var c = 30;
        // var d = 5;
        // var e = (a+b+c+d);
        // console.log (e);

        // Chapter No (4)

        // Variable Mistakes!

        // var jibranJabbar Galat ! jibranJabbar Sai! Camel Example! 

        // var 1ali () ?ali () Galat me kia shamil hain ! ali1 () &ali () Sai ! !

        // Camel Case Example

        // var chatApp = 5;
        // Good Practice!

        // Chapter No (5,7)!

        // var x = 20;
        // var y = "10"
        // var z = x+y;
        // alert (z);

        // var x = 20;
        // var y = "2"
        // var z = x*y;
        // alert (z);

        // var x = 20;
        // var y = "2"
        // var z = x/y;
        // alert (z);

        //  var x = 4;
        //  var y = "2"
        //  var z = x-y;
        //  alert (z);

        // BodMass Rule!

        // Division.
        // Multiplication.
        // Addition. 
        // Subtraction.

        //  var a = 3;
        //  var b = 5;
        //  var c = 7;
        //  var d = b-a*c;
        //  alert(d);

        // var a = 3;
        // var b = 5;
        // var c = 7;
        // var d = (b-a)*c;
        // alert(d);

        // Chapter No (6)!

        // Post Increament!

        //  var a = 5;
        //  var b = a++;
        //  alert (b);

        // Num = Num + 1;

        //Post Decriment!

        // var a = 5;
        // var b = a--;
        // alert (b);

        // Num = Num - 1;

        //Pre Increament!

        // var x = 5;
        // var y = ++x;
        // alert(y);

        //Pre Decriment!

        // var x = 5;
        // var y = --x;
        // alert(y);

        // Example!

        // var x = 10;
        // var y = x++ + ++x - x + x++ - ++x + x;
        // 10 + 12 - 12 + 12 - 14 + 14;  22 Answer!
        // var z = alert(y);

        //var x = 10;
        //var y = x-- + --x - x + x-- - --x + x;
        // 10 + 8 - 8 + 8 - 6 + 6;   18 Answer!
        //var z = alert(y);

        //var x = 5;
        //var y = x++ + ++x + x + --x + x-- - x;
        // 5 + 7 + 7 + 6 + 6 - 5   26 Answer!
        //alert(y);

        // Chapter No = (8)!

        // var x = 20;
        // var y = "10"
        // var z = x+y;
        // alert (z);

        // var a = "Jibran";
        // var b = 5;
        // var c = a+b;
        // alert(c);

        //Chapter No (9)!

        // var a = prompt("Enter Your Value","Your Value Is:");
        // var b = 10;
        // var c = a+b;
        // alert(c);

        // var a = +prompt("Enter Your Value","Your Value Is:");
        // var b = 10;
        // var c = a+b;
        // alert(c);

        // var a = -prompt("Enter Your Age","Your Age Is:");
        // var b = a+2;
        // console.log(b);

        // var d = "Enter Your Value";
        // var e = "Your Value Is:";
        // var a = +prompt(d,e);
        // var b = 10;
        // var c = a+b;
        // alert(c);

        // var a = "Enter Your Value";
        // var b = "Your Value Is:";
        // var c = +prompt(a,b);
        // var d = c+50;
        // console.log("Your Value Is:", + " " + d);

        // var a = "Enter Your Value";
        // var b = "Your Value Is:";
        // var c = +prompt(a,b);
        // var d = c+50;
        // console.log("Your Value Is:",d);

        // var a = "Enter Your Value";
        // var b = "Your Value Is:";
        // var c = +prompt(a,b);
        // var d = c+50;
        // document.write("Your Value Is:",d);

        //Chapter No (10)!

        // var age = 16;

        // if(age == 16){
        //    alert("Your Age Is Less")
        // }
        // else{
        //     alert("You Are No More With Less Age")
        // }

        // var age = 14;

        // if(age < 15){
        //    alert("Your Age Is Less")
        // }
        // else{
        //     alert("You Are No More With Less Age")
        // }

        // var age = 40;

        // if(age > 41){
        //    alert("Your Age Is Less")
        // }
        // else{
        //     alert("You Are No More With Less Age")
        // }


        //Chapter No (11)!

        // > Is Greater Than
        // < Is Less Than
        // >= Is greater Than Or Equal To
        // <= Is Less Than Or Equal To

        //Chapter No (12)!


        // var age = +prompt("Enter Your Age","Your Age Is:")

        // if(age == 15){
        //    alert("Your Age Is Equal")
        // }

        // else if(age < 15 ){
        //     alert("Your Age Is Less")
        // }

        // else{
        //     alert("You Are No More With Less Age")
        // }

        // var a = "Enter Your Age";
        // var b = "Your Age Is:";
        // var age = +prompt(a,b)

        // if(age == 15){
        //    alert("Your Age Is Equal")
        // }

        // else if(age < 15 ){
        //     alert("Your Age Is Less")
        // }

        // else {
        //     alert("You Are No More With Less Age")
        // }

        // var a = "Enter Your Age";
        // var b = "Your Age Is:";
        // var age = +prompt(a,b)

        // if(age == 15){
        //    alert("Your Age Is Equal")
        // }

        // else if(age < 15 ){
        //     alert("Your Age Is Less")
        // }

        // else {
        //     alert("You Age Is More")
        // }

        //Chapter No (13)!

        // var age = +prompt("Enter Your Age","Your Age Is:");

        // var gender = prompt("Enter Your Gender","Your Gender Is:");

        // if (age > 18 && gender == "Male"){
        //     alert("You Are Allowed!")
        // }
        // else{
        //     alert("You Are Not Allowed!")
        // }

        // var age = +prompt("Enter Your Age","Your Age Is:");

        // var gender = prompt("Enter Your Gender","Your Gender Is:");

        // if (age > 18 || gender == "Male"){
        //     alert("You Are Allowed!")
        // }
        // else{
        //     alert("You Are Not Allowed!")
        // }

        // var age = +prompt ("Enter Your Age","Your Age Is:");
        // var gender = prompt ("Enter Your Gender","Your gender Is:");

        // if (age >18 && gender === "Male"){
        //     alert("Correct");
        // }

        // var a = "5";
        // if (a !== 5){
        //     alert("correct")
        // }
        // else{
        //     alert("Incorrect")
        // }

        // var a = "5";
        // if (a == 5){
        //     alert("True")
        // }
        // else{
        //     alert("False")
        // }

        // var a = "5";
        // if (a === 5){
        //     alert("True")
        // }
        // else{
        //     alert("False")
        // }

        //  var a = "English";
        //  if (a === "English")
        //  {
        //     alert("Correct")
        // }
        // else{
        //     alert("Incorrect")
        // }

        // var a = 5;
        // var b = 10;
        // var c = 15;
        // var d = 10;

        // if (b-a === c-d ){
        //     alert("Correct!")
        // }
        // else{
        //     alert("Incorrect!")
        // }

        //  var a = 5;
        //  var b = 10;
        //  var c = 30;
        //  var d = 15;

        // if (b+a === c-d ){
        //     alert("Correct!")
        // }
        // else{
        //      alert("Incorrect!")
        //  }

        //  var a = 5;
        //  var b = 10;
        //  var c = 15;
        //  var d = 15;

        // if (b+a === c-d ){
        //     document.write("Correct!")
        // }
        // else{
        //      document.write("Incorrect!")
        //  }


        // var a = 10;

        // if (a !== 15 ){
        //     document.write("Correct!")
        // }
        // else{
        //      document.write("Incorrect!")
        //  }

        // var age = +prompt("Enter Your Age");

        // var gender = prompt("Enter Your Gender");

        // var qualification = prompt("Enter Your Qualification");

        // var country = prompt("Enter Your Country")

        // if(age >= 15 && gender === "Male" && qualification === "Matriculation" && country === "Pakistan"  ){
        //     alert("You Are Succes Full!")
        // }
        // else{
        //     alert("You Are Not Succes Full!")
        // }

        // var age = +prompt("Enter Your Age");

        // var gender = prompt("Enter Your Gender");

        // var qualification = prompt("Enter Your Qualification");

        // var country = prompt("Enter Your Country")

        // if(age >= 15 || gender === "Male" || qualification === "Matriculation" || country === "Pakistan"  ){
        //     alert("You Are Succes Full!")
        // }
        // else{
        //     alert("You Are Not Succes Full!")
        // }


        // var age = +prompt("Enter Your Age");

        // var gender = prompt("Enter Your Gender");

        // var country = prompt("Enter Your Country")

        // if(age >= 15 || gender === "Male" && country === "Pakistan"  ){
        //     alert("You Are Succes Full!")
        // }
        // else{
        //     alert("You Are Not Succes Full!")
        // }

        // var age = +prompt("Enter Your Age");

        // var gender = prompt("Enter Your Gender");

        // var country = prompt("Enter Your Country")

        // if((age >= 15 || gender === "Male") && country === "Pakistan"  ){
        //     alert("You Are Succes Full!")
        // }
        // else{
        //     alert("You Are Not Succes Full!")
        // }

        // var age = +prompt("Enter Your Age");

        // var gender = prompt("Enter Your Gender");

        // var country = prompt("Enter Your Country")

        // if(age >= 15 || gender === "Male" ( country === "Pakistan")  ){
        //     alert("You Are Succes Full!")
        // }
        // else{
        //     alert("You Are Not Succes Full!")
        // }

        // var percent = +prompt("Enter Your Percent","Your Percent Is:")

        // if(percent >= 80 && percent <= 100){
        //     alert("A+")
        // }
        // else if (percent >= 70 && percent <= 80){
        //     alert("A")
        // }
        // else if (percent >= 60 && percent <= 70){
        //     alert("B")
        // }
        // else if (percent >= 50 && percent <= 60){
        //     alert("C")
        // }
        // else if (percent >= 40 && percent <= 50){
        //     alert("D")
        // }
        // else if (percent >= 33 && percent <= 40){
        //     alert("E")
        // }
        // else if (percent >= 0 && percent <= 33){
        //     alert("Fail")
        // }
        // else {
        //     alert("You Did Not Write Correct Percentage! ")
        // }

        //Chapter No (14)!

        // var a = 5;
        // var b = 5;
        // var c = a+b;
        // var d = 6;
        // var e = 4;
        // var f = d+e;


        // var g = 10;
        // var h = 10;
        // var i = g+h;
        // var j = 15;
        // var k = 5;
        // var l = j+k;

        // var m = 15;
        // var n = 15;
        // var o = m+n;
        // var p = 10;
        // var q = 20;
        // var r = p+q;

        // if(c === f){
        //     if (i === l)
        //     {
        //         document.write("You Are SuccesFull")
        //     }
        //     else if(o === r)
        //     {
        //         document.write("You Are SuccesFull")
        //     }
        //     else{
        //         document.write("You Are Not SuccesFull")
        //     }
        // }
        // else{
        //     document.write("You Are Not SuccesFull")
        // }


        // var age = +prompt("Enter Your Age");

        // var gender = prompt("Enter Your Gender");

        // var country = prompt("Enter Your Country")

        // if(age >= 15 || gender === "Male" ( country === "Pakistan")  ){
        //     alert("You Are Succes Full!")
        // }
        // else{
        //     alert("You Are Not Succes Full!")
        // }

        //         var user = prompt("Enter Your Value","Your Value Is:")

        // if (user === "Vatican"){
        //    alert(score = 1)
        //    alert(userIQ = "Genius")
        //     alert("Good")
        // }

// Correct Answer InCorrect Answer Application Q/A!

// var score = 0;
// var userIQ = '';
// var User = prompt("Q1: Which Is The Best Programing Language Of The World",)
// if(User === "JavaScript"){
//    score++ 
//    userIQ = 'Genius'
//    alert('Score : ' + " " + score + " " + " : " + " " + 'UserIQ : ' + " " + userIQ + " " + " : " + " " + "Correct Answer!" )
// }
// else if (User === "") {
//     alert('Valid This Feild!')
// }
// else{
//     score--
//     userIQ = 'Bad'
//     alert('Score : ' + " " + score + " " + " : " + " " + 'UserIQ : ' + " " + userIQ + " " + " : " + " " + "InCorrect Answer!" )
// }

        //Chapter No(15)!

        //Syntacs By Array!

//Array Hamesha Object Hi return Karta Ha OK!

        // var name = "Mark"
        // alert(name)

        // var a = "Jibran"
        // var b = "Ali Bhai"
        // var c = "Hayyan"
        // var d = a+b+c
        // alert(d)

        // var a = ["Jibran","Hayyan","Ali Bhai"];
        // document .write(a);

        // var Students = ["Jibran","Hayyan","Ali Bhai"];
        // console.log(Students[1]);


        // var Students = ["Jibran","Hayyan","Ali Bhai"];
        // alert("Welcome " + Students[1]);

        //By The Effect String!

        // var Students = ["Jibran","Hayyan","Ali Bhai",123];
        // alert("Welcome " + Students[3]);

        //Chapter No(16)!

        // var names = [];

        // names [0] = "Hayyan";
        // names [1] = "Jibran";
        // names [2] = "Ahsan";
        // names [3] = "Ali";
        // names [4] = "Osama";

        // document.write(names);

        //Last Word  Hide Karne Ka Liyen!

        // var Students = ["Jibran","Hayyan","Ali Bhai"];

        // Students.pop()

        // console.log(Students);

        //Last Me Word Add Karne Ke Liyen!

        // var Students = ["Jibran","Hayyan","Ali Bhai"];

        // Students.push("Osama")

        // console.log(Students);

        //  var Students = ["Jibran","Hayyan","Ali Bhai"];

        //  Students.push("Osama","Ahsan")

        //  console.log(Students);

        //Chapter No (17)!

        //Remove From Start!

        // var Students = ["Jibran","Hayyan","Ali Bhai"];

        // Students.shift()

        // console.log(Students);

        //Starting From Add Word!

        // var Students = ["Jibran","Hayyan","Ali Bhai"];

        // Students.unshift("Osama","Ahsan")

        // console.log(Students);

        //1st wale ko remove nhi karo is ke baad osama add kardo!

        // var Students = ["Jibran","Hayyan","Ali"];

        // Students.splice(1,0,"Osama")

        // console.log(Students);

        //1st Wale Ko Remove Kar Ke Osama Add Kardo!

        // var Students = ["Jibran","Hayyan","Ali"];

        // Students.splice(0,1,"Osama")

        // console.log(Students);

        //2nd wale ko remove karke osama add kardo!

        //  var Students = ["Jibran","Hayyan","Ali"];

        //  Students.splice(1,1,"Osama")

        //  console.log(Students);

        // 2 Word Ko Esse Delete Karta Hain! or One Word Add Karta Hain do ka bajae!

        // var Students = ["Jibran","Hayyan","Ali"];

        // Students.splice(0,2,"Osama")

        // console.log(Students);

        //2nd Wale Ko Remove Kardo!

        // var Students = ["Jibran","Hayyan","Ali"];

        //  Students.splice(1,1,)

        // console.log(Students);

        //Ek Value Ko Copy Kar Ke Dosri Value Me Kese Pest Karen

        // var Students = ["Jibran","Hayyan","Ahsan","Ali","Osama"];

        // var copyStudents = Students.slice(1,4);

        // console.log(Students);

        // console.log(copyStudents);

        // var arr= ["Dog","Cow","Leopard","Tiger","Lion"];
        // arr[5] = "Cat";
        // arr[6] = "Elephant";
        // console.log(arr)

        // var arr1 = new Array ("Jibran","Hayyan","Ahsan","Ali","Osama")
        // console.log(arr1)

// var arr = [{name: 'Mark',Father_Name: 'Ace'},"This Is Object",{Age: '18',Class: 'IX (9th)'},'This Is Example By Array To Obj!']

// console.log(arr)

        // Object Ke Ander Hum Array Bhi Bana Sakte Hain Our Array Ke Ander Hum Object Bhi Bana Sakte Hain OK!
 
        //Chapter No(18 For Loop)!

        //for(initialization ; condition ; Increament/Decreament){
        // document.write(a)
        //}

        // var user = prompt("Enter Your City")

        // var Cities = ["Karachi","Hyderabad","Islamabad","London","Paris"];
        //  if (user === Cities[0]) {
        //  alert("It's one of the cleanest cities");
        //  }
        //  else if (user === Cities[1]) {
        //  alert("It's one of the cleanest cities");
        //  }
        //  else if (user === Cities[2]) {
        //  alert("It's one of the cleanest cities");
        //  }
        //  else if (user === Cities[3]) {
        //  alert("It's one of the cleanest cities");
        //  }
        //  else if (user === Cities[4]) {
        //  alert("It's one of the cleanest cities");
        //  }

        //  else {
        //  alert("It's not on the list");8 }



        // var user = prompt("Enter Your City")

        // var Cities = ["Karachi","Hyderabad","Islamabad","London","Paris"];


        // for(var i= 0; i<=user.length; i++){
        // if (user === Cities[i]){
        //     alert("It's one of the cleanest cities");
        // }
        // }

        // var a ;
        // for (a = 1 ; a <= 10 ; a++ ){
        //     document.write(a + "<br>")
        // }

        // var b = 10;
        // for (;b >= 1 ; b--){
        //     document.write(b + "<br>")
        // }

        // This Is A For Loops Binifits KeyWord For JavaScript!

        // for (var a = 1; a <= 5 ; a++){
        //     document.write("Hello World" + "<br>")
        // }

        // document.write("Hello World" + "<br>")
        // document.write("Hello World" + "<br>")
        // document.write("Hello World" + "<br>")
        // document.write("Hello World" + "<br>")
        // document.write("Hello World" + "<br>")

        // for(var a = 1; a<= 10; a++){
        // document.write("Hello Jibran!"  + "<br>" + "<br>" + "<br>" + "<br>")
        // }




        // for(var a = 1 ; a <= 10 ; a++){
        //     document.write(a + "<br>")
        // }

        //1
        //2
        //3
        //4
        //5
        //6
        //7
        //8
        //9
        //10

        // for (var b = 10 ; b >= 1 ; b--){
        //     document.write(b + "<br>")
        // }

        //10
        //9
        //8
        //7
        //6
        //5
        //4
        //3
        //2
        //1

        // Time By Time Chal Raha Ha! ^Top

        // var a;
        // for (a = 1; a <= 10 ; a= a+2){
        //     document.write(a + "<br>")
        // };

        // var a = 2;
        // for(a<=20; a= a+2;){
        //     document.write(a + "<br>")
        // }

        // Tables By Work On JavaScript!

        //  var a;
        //  for (a = 1; a <= 10 ; a= a+1){
        //      document.write(a + "<br><br>")
        //  }


        //  var a;
        //  for (a = 2; a <= 20 ; a= a+2){
        //      document.write(a + "<br><br>")
        //  } 

        //  var a;
        //  for (a = 3; a <= 30 ; a= a+3){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 4; a <= 40 ; a= a+4){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 5; a <= 50 ; a= a+5){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 6; a <= 60 ; a= a+6){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 7; a <= 70 ; a= a+7){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 8; a <= 80 ; a= a+8){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 9; a <= 90 ; a= a+9){
        //      document.write(a + "<br><br>")
        //  }

        //  var a;
        //  for (a = 10; a <= 100 ; a= a+10){
        //      document.write(a + "<br><br>")
        //  }
        //Etc!
        // document.write("2" + "x" + "1" + "=" + 2*1 + "<br>")
        // document.write("2" + "x" + "2" + "=" + 2*2 + "<br>")
        // document.write("2" + "x" + "3" + "=" + 2*3 + "<br>")
        // document.write("2" + "x" + "4" + "=" + 2*4 + "<br>")
        // document.write("2" + "x" + "5" + "=" + 2*5 + "<br>")
        // document.write("2" + "x" + "6" + "=" + 2*6 + "<br>")
        // document.write("2" + "x" + "7" + "=" + 2*7 + "<br>")
        // document.write("2" + "x" + "8" + "=" + 2*8 + "<br>")
        // document.write("2" + "x" + "9" + "=" + 2*9 + "<br>")
        // document.write("2" + "x" + "10" + "=" + 2*10 + "<br>")

        //Shorten Table!

        // for (a = 1; a<=10; a+ a+1){
        //     document.write("2" + "x" + a + "=" + 2*a + "<br>")
        // }

        // for (var a = 0; a <= 10; a= a+1){
        //     document.write(a );
        // }

        // for (var i = 1; i <= 10 ; i++){
        //     document.write("2" + "x" + i + "=" + 2*i + "<br>")
        // }

        // for(var a = 1 ; a <= 10; a= a+1){
        //     document.write("2" + "x" + a + "=" + 2*a + "<br>" )
        // }

        // var Students = ["Jibran ","Hayyan","Ali Bhai","Ahsan","Osama","Hammad","Sufiyan","Hussain","Azaan"];
        // console.log(Students[0]);
        // console.log(Students[1]);
        // console.log(Students[2]);
        // console.log(Students[3]);
        // console.log(Students[4]);
        // console.log(Students[5]);
        // console.log(Students[6]);
        // console.log(Students[7]);
        // console.log(Students[8]);

        // var Students = ["Jibran","Hayyan","Ali Bhai","Ahsan","Osama","Hammad","Sufiyan","Hussain","Azaan"];

        // for (var a = 0; a < Students.length; a++){
        //     document.write(Students[a])

        // }

        // var cities = ["Karachi","Lahore","Islamabad","Faisalabad","Kashmir"]

        // for (var a = 0 ; a < cities.length ; a++){
        //     if(cities[a] === "Karachi" ){
        //         document.write(cities[a] + " Is a Cleanest City!")
        //     }
        // }

        //      var City = prompt("Enter Your City","Your City Is:");
        //   var arr = ["Karachi","Hyderabad","Islamabad","London","Paris","Lahore","NewYork","Honkgonk"];
        //   for (var a = 0; a<=arr.length; a++){
        //   if (City === arr[a]){
        //        document.write("The Question" +" "+ arr[a] + " " + "Is Right!")
        //   }
        // }


        // for(var i = 1; i>0; i++){
        // console.log("Hello World" + "<br>")
        // }

        //counting stop karne ke lian  break kara!

        // for(var i = 1; i>=0; i++){
        //     if(i === 10){
        // break
        //     }
        // document.write("Hello World" + "<br>" + "<br>")
        // }

        //     for (var a = 1; a>= 0;a++){

        //         if(a === 5){

        //    break
        //         }
        //         console.log("Hello World")

        //     }

        // for (var i = 0; i<10; i++){
        //     if(i ===5 ){
        // break
        //     }
        //     console.log("Hello Word")
        // }

        // var City = prompt("Enter Your City", "Your City Is:");
        // var arr = ["Karachi"];
        // for (var a = 0; a < arr.length; a++) {
        //     if (City === arr[a]) {
        //         document.write("The Question" + " " + arr[a] + " " + "Is Correct!")
        //         break
        //     }
        //     else {
        //         document.write("The Question" + " " + City + " " + "Is  InCorrect!")
        //         break
        //     }
        // }


        // For Loop Nested

        // for (var i = 0; i< 2; i++){
        //   for (var a = 0; a< 3; a++){
        //     console.log 
        //     ("Pakistan Zindabad")
        //   }
        // }



        // for (var a = 1;a<=5;a++){
        // for(var a = 1; a<=3;a++){
        // document.write("Zindabad,,,,,,,,,")
        //   }
        // }

        // for (var a =  0 ; a <= 5; a++) {
        //     for (var b = 0 ; b <= 3; b++) {
        //         document.write("Zindabat,,,,,,,!" + "<br>" + "<br>")
        //     }
        // }

        // var firstName = ["Jibran", "Hayyan", "Ali", "Osama"]
        // var lastName = ["Abdul Jabbar", "Abdul Jabbar", "Abdul Jabbar", "Abdul Jabbar"]
        // for (var i = 0; i < firstName.length; i++) {
        //     for (var a = 0; a < lastName.length; a++) {
        //         document.write(firstName[i] + " " + lastName[a] + "<br>" + "<br>")
        //     }
        // }


        //    var firstName = ["Jibran", "Hayyan", "Ali"]
        //      var lastName = ["Abdul Jabbar","Khan"]
        //  for (var i = 0; i < firstName.length; i++) {
        //      for (var a = 0; a < lastName.length; a++) {
        //              document.write(firstName[i] + " " + lastName[a] + "<br>" + "<br>")
        //          }
        //      }

        // var firstName = ["Jibran", "Hayyan", "Ali"]
        //      var lastName = ["Abdul Jabbar"]
        //  for (var i = 0; i < firstName.length; i++) {
        //      for (var a = 0; a < lastName.length; a++) {
        //              document.write(firstName[i] + " " + lastName[a] + "<br>" + "<br>")
        //          }
        //      }

        //For loop Practice By Full


        // function rol (){
        //     var input= prompt("Please Type A Table Number")
        //     var length= prompt("Please Type A length Number")

        // var a;
        //        for (a = 1; a <=length ;  a++){

        //         if(input===""){
        //             alert("Please relode the page and fill out this input field")

        //     break
        //         }
        //           document.write( input*a  + "<br>"+"<br>")

        //       } 

        // }



        // function col (){
        // var input = prompt("Please Type A Table Number")
        // var length = prompt("Please Type A length Number")

        // var a;
        // for (a = 1; a <= length; a++) {

        //     if (input==="" || length === "" ) {
        //         alert("Please relode the page and fill out this input field")

        //     break
        //     }
        //     document.write(input + " x " + a  + " = " + input * a + "<br>" + "<br>")

        // }
        // }

        // col()



        // for(var i = 1; i <=10; i++ ){
        //    for(var a = 1; a<=i; a++){
        // document.write("*")
        // }
        // document.write("<br>")
        //     }
        //jibranabduljabbar

        //Method by 

        // for(var i = 1; i<=10;i++){
        // for(var   a = 1 ; a<=i; a++){
        //     for(var  b= 1; b<=a;b++){
        //         document.write(  "*" )
        //     }
        // }
        // document.write("<br>")
        // }

        // "Civic"==="civiC"
        // "MadaM"==="MadaM"
        //"Refer"==="refeR"
        // "Palindromes Words Dono Taraf Se Ek Jese Words Ko Kehte Hain"

        //Chap=Changing Case 21

        // jis tarah hum array ka index number pass kar rahe the essi tarah hum string ka index number bhi pass kar sakte hain!

        // var name ="Jibran";

        // document.write(name[0])
        // document.write(name[1])
        // document.write(name[2])
        // document.write(name[3])
        // document.write(name[4])
        // document.write(name[5])

        // var word = prompt("Enter Your Word")
        // var check = "";
        // for(var i = word.length -1;i>=0;i--){
        // check += word[i]
        // }

        // if(check=== word){
        // console.log(word+" "+"Is Palindrome Word")
        // }

        //Application by palindrome word

        // var user = prompt("Enter Your Word!","Your Word Is:");
        // var check = "";
        // for(var i = user.length - 1 ; i>=0 ; i--){
        //  check += user[i]

        // }
        // if(check === user){
        // alert(user+" Is Palindrome Word")
        // }
        // else{
        //     alert(user + " Is not a Plindrome word")
        // }



        // var name = "JIBRAN";
        // name = name.toLowerCase()
        //  console.log(name)

        //  var name = "jibran";
        // name = name.toUpperCase()
        //  console.log(name)


        //  var name = ["jibran","HAYYAN"];
        // name = name.toUpperCase()
        //  console.log(name)

        // String ke ander bhi haum value add karasakte hain jese hum array me kar rahe the!

        // var name = "jibran";
        // var name1 = name.slice(0,5)
        // console.log(name)
        // console.log(name1)

        // var name = "Jibran Abdul Jabbar";
        // var name1 = name.slice(13,19)
        // console.log(name)
        // console.log(name1)

        //Chap 23 Finding Segments

        //Kesi bhi word ka Index number pouchne ke lien ye method istamaal hoga indexOf()
        //String me bhale space ho ye usko bhi count kare ga space ko bhi

        // var name = "Jibran Abdul Jabbar";
        // console.log(name.indexOf("l")) // l 11 number per ha

        //Basic Calculator Application

        // var num1 = prompt("Enter Your Number1");
        // var Sign = prompt("Enter Your Operator");
        // var num2 = prompt("Enter Your Number2");

        // console.log(num1+Sign+num2);

        // if(Sign === "+"){
        // alert((+num1)+(+num2))
        // }
        // else if(Sign === "-"){
        // alert(num1-num2)
        // }
        // else if(Sign === "*"){
        // alert(num1*num2)
        // }
        // else if(Sign === "/"){
        // alert(num1/num2)
        // }
        // else if(Sign === "%"){
        // alert(num1%num2)
        // }
        // else if(Sign==="%"){
        // alert(num1/num2*100 + "%")
        // }

        // Abhi ye pharna ha!

        // var cal = prompt("Enter Your Calculate Value");
        // for(var i = 0; i<cal.length ; i++){
        // if(cal.slice(i,i+1)==="+"||cal.slice(i,i+1)==="-"||cal.slice(i,i+1)==="*"||cal.slice(i,i+1)==="/"||cal.slice(i,i+1)==="%"){
        // alert("Thank For Visiting")
        // }
        // }

        // var cal = prompt("Enter Your Calculate Value");
        // var num = cal.length;
        // for(var i = 0; i<num ; i++){
        // if(cal.slice(i,i+1)==="+"||cal.slice(i,i+1)==="-"||cal.slice(i,i+1)==="*"||cal.slice(i,i+1)==="/"||cal.slice(i,i+1)==="%"){
        // alert("Thank For Visiting")
        // }
        // }

        //2:39:26

        //Assignment By Mohammad Ali Mughal!

        // for (var i = 1 ; i<= 100 ; i= i+10){
        // for(var a = i; a < i+10; a++){
        // document.write(a + " ")
        // }
        // document.write("<br>")
        // }

        // AppliCation For City toLowerCase toUpperCase!

        // var city = prompt('Enter Your City!')
        // city = city.toLowerCase()
        // var cities = ['karachi']

        // for(var i =  0; i<cities.length; i++){
        // if(cities[i] === city){
        // alert("City has Found!")

        // }
        // else{
        //     alert("City has Not Found!")
        // }
        // }

        ///

        //Concatinate Karwa Ya Ha & Chapter Mee Jo ha!

        // var city = prompt('Enter Your City!')
        // var firstChar = city.slice(0,1);
        // var secondChar = city.slice(1);
        // firstChar= firstChar.toUpperCase();
        // secondChar= secondChar.toLowerCase();

        // var city = firstChar+secondChar

        // var cities = ['Karachi',]
        // for(var i =  0; i<cities.length; i++){
        // if(cities[i] === city){
        // alert("City has Found!")

        // }
        // else{
        //     alert("City has Not Found!")
        // }
        // }


        // var user = prompt("Enter Your Value!")

        // for(var i =  0; i<user.length; i++){
        // if(user.slice(i, i + 2) === "  "){
        // alert("Don't Type Space!")
        // break
        // }
        // }

        // Replecing Words How To Replace The Words!

        //     var user = "How Are You Jibran!"
        //     for ( var i = 0 ; i < user.length; i++ ){
        //         if (user.slice(i, i + 6) === "Jibran") {
        //     // user = user.slice(0, i) + "Lodhi!" + user.slice(i + 6);
        //    user = user.slice(0, i) + "Hayyan" + user.slice(i + 6);
        //     console.log(user)
        //         }
        //     }

        //  Replecing Words How To Replace The Words Second Tarika indexOf ke zeriye!

        // var text = "The Pakistan Zindabad Is Great Country Of The World!"
        // var check = text.indexOf("Pakistan Zindabad")
        // var firstText = text.slice(0,check)
        // var replecing = "Hello Pakistan";
        // var thirdText = text.slice(check+17)

        // console.log(firstText+replecing+thirdText)

        // ye last index se shuru kare ga our jo isse mile ga shuru me word wo usse replace karde ga lastIndexOf!

        // var text = "The Pakistan Zindabad Is Great a Pakistan Zindabad Country Of The World!"
        // var check = text.lastIndexOf("Pakistan Zindabad")
        // var firstText = text.slice(0,check)
        // var replecing = "Hello Pakistan";
        // var thirdText = text.slice(check+17)

        // console.log(firstText+replecing+thirdText)

        //charAt As A Function ha is me hum index pass karte hain our us index ki value get karte hain! 

        // var lname = "Ace";
        // console.log(fname.charAt(3))

        // var fname = "Mark";
        // console.log(fname.charAt(2))

        //agr kisi ko replace karna ho var ke String me To Kese Karenge us Ke Lia Hamare pass ek function ha replace() jo ke value ko replace kar ke nai value add kar deta ha!

        // var fName = "This is Example!";
        // var replaceName = fName.replace("Example!","2nd") 
        // console.log(replaceName)

        // var lname = "This Is 2nd Example";
        // var replaceName = lname.replace("2nd","3rd")
        // console.log(replaceName)

        // var fName = "This is Example! This is Example!";
        // var replaceName = fName.replace("Example!","2nd") 
        // console.log(replaceName)

        //Ab jahan jahan is ko example mila ga wo us ko replace kar wade ga! is ka medhod ha //g

        // var fName = "This is Example! This is Example!";
        // var replaceName = fName.replace(/Example!/g,"2nd") 
        // console.log(replaceName)

        // var lname = "This Is Example This Is Example"
        // var replaceWord = lname.replace(/Example/g,"1st Example")
        // console.log(replaceWord)

        //1.5 se niche hogi value to ye 1 dekhay ga our 1.5 se upper hogi value to 2 hoga ok our 1.-1 to value 0 me aaygi our ye method hum Math.round me karte hain!

        // var value = 1.1;
        // var mathRound = Math.round(value);
        // console.log(mathRound)

        // math.ceil karta ha ye ke 1.5 ho ya 1.2 ho wo hamesha hamein bari value autha ke dega yani ke 2 ab bhale wo value 1.5 hoya 1.8 ye hamein 2 number lake dega! 

        // var value = 1.98797897;
        // var mathRound = Math.ceil(value);
        // console.log(mathRound)

        // math.floor ye kia karta ha jis tarike se math.ceil hamein Bari value utha ke de raha tha essi tarah hamain math.floor hamein choti value utha ke dega ab bhale wo 1. ke bad koi sa bhi number aay 1 ayyga!

        // var value = 1.54546;
        // var mathRound = Math.floor(value);
        // console.log(mathRound)

        // math.random hamein ek nai id generet kar ke deta ha yani ke new roll number add kar ke deta ha! 

        //  Math.random() // is method ko console pe chalaen!

        // for Example ye ye karta ha!

        // Math.random()
        // 0.12726965760707198
        // Math.random()
        // 0.1531834137133028
        // Math.random()
        // 0.2349221983466101
        // Math.random()
        // 0.32700160547885804
        // Math.random()
        // 0.8340087803445775
        // Math.random()
        // 0.020471514686773995

        //New Roll Generet kar raha ha!

        // Math.random() * 2
        // 0.12726965760707198


        // Math.random() * 2
        // 0.97426965760707794


        // Math.random() * 2
        // 0.08466965760709922


        // Math.random() * 2
        // 0.982369997630759198

        // Examples 

        //New Work

        // var headUser = prompt("Enter Head Username");
        // var tailUser = prompt("Enter Tail Username");

        // var round = Math.random() * 2;
        // var math_floor = Math.floor(round)
        // console.log(math_floor)


        // Game Application Heads Teals! 

        // var headUser = prompt("Enter Head Username");
        // var tailUser = prompt("Enter Tail Username");

        // var round = Math.random() * 2;
        // var math_floor = Math.floor(round)
        // if (math_floor === 0) {
        // alert(" Heads " + headUser + " Win the Toss ")
        // }
        // else{
        //     alert(" Tails " + tailUser + " Win the Toss ")
        // }
        // console.log(math_floor)

        ////////////////////////////////////

        // var headUser = prompt("Enter Head Username");
        // var tailUser = prompt("Enter Tail Username");
        // var Math_random = Math.random() *2
        // var Math_floor = Math.floor(Math_random)
        // if(Math_floor === 0){
        //     alert("Heads " + headUser + " User Win The Tool")
        // }
        // else{
        //     alert("Tails " + tailUser + " User Win The Tool")
        // }
        // console.log(Math_floor)

        //Number ya parseInt ye method Strings Value ko Numeric value me convert kardeta ha!

        // var value =  Number("1.543556354546642")
        // console.log(value)

        // var value =  Number("10")
        // console.log(value)

        //  var value =  parseInt("5435232")
        //  console.log(value)

        // var value = parseFloat("3245332")
        // console.log(value)

        // Numeric value ko String me Convert Karna ho to 10.to.String() ka method use karna parega!

        // var value = 10
        // console.log(value.toString(value))

        //toFixed me 1 number our bhi add kare ga!

        // var value = 10.54543232;
        // var round = value.toFixed(2)
        // console.log(round)

        // var value = 10.54543232;
        // var round = value.toFixed(3)
        // console.log(round)

        //Ye Kia Kare Ga Hamein Live DateTimeYear Nikal Ke De Dega!

        // var dateTimeDay = new Date()
        // console.log(dateTimeDay)

        // var dateYearTime = new Date();
        // var b =  dateYearTime.toString()
        // var c = b.slice(0,3)
        // console.log(c)

        // Check By Console.log 

        // Get Day Hamaroko Live Day Ka Index Number La ke De de Ga!

        // var date = new Date()
        // var getday = date.getDay()
        // console.log(getday)

        //Day Ke Bhi Index number hote hain Hote Hain Index 

        // Sunday Ka index Number (0)
        // Monday Ka index Number (1)
        // Tuesday Ka index Number (2)
        // Wednesday Ka index Number (3)
        // Thursday Ka index Number (4)
        // Friday Ka index Number (5)
        // Saturday Ka index Number (6)

        //jab hamein index number ki value check karni hoto hamne ek array banani paregi

        // var dayNames = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
        // var newdate = new Date();
        // var getday = newdate.getDay();
        // var mixing = dayNames[getday];
        // console.log(mixing)

        // getDay() ki jaga hum our bhi chizen check kar sakte hain yani ke

        //  Method                 Gets             Range                  Example

        // getDay() //            Day of week          1-6                 0 is Sunday
        // getMonth() //          Month                0-11                0 is January
        // getDate() //           Day of week          1-31                1 is 1st of Month
        // getFullYear() //       Year                                     2020
        // getHours() //          Hour                 0 - 23              0 is Midnight
        //                                                               12 is Noon
        //                                                               23 is 11 P.m  
        // getMinutes() //        Minute               0 - 59
        // getSeconds() //        Second               0 - 59
        // getMilliseconds() //   Millisecond          0 - 999
        // getTime() //            Milliseconds since midnight, January 1, 1970

        // main Structure Of Date

        // This Is Application Of Ap kitne Year Ke Ho Gay Ho Chekh Karne Ke Liyen

        // var dateOfBirth = new Date(prompt("Enter Your Date Of Birth","Oct 30, 2006"))
        // var dateOfBirth_Get = dateOfBirth.getTime()
        // var liveDateTime = new Date()
        // var liveDateTime_Get = liveDateTime.getTime()
        // var diff = liveDateTime_Get - dateOfBirth_Get
        // var diffYear = diff/(1000*60*60*24*30*12)
        // var ValueMinas = Math.floor(diffYear)
        // console.log(ValueMinas)

        // Short Code From This Application 

        // var dateOfBirthAndChanges = new Date().getTime() - new Date(prompt("Enter Your Date Of Birth","Oct 30, 2006")).getTime() ;
        // var dateOfBirthAndChangesMathFloorBodmassValue = Math.floor(dateOfBirthAndChanges / (1000 * 60 * 60 * 24 * 30 * 12));
        // console.log(dateOfBirthAndChangesMathFloorBodmassValue)

        // Agr Mujhe Ye Maloom Karna Hoo Ke me Kon Se Din Peda Hoa Tha!

        // var ApniMarziKaTime = new Date("Oct 30, 2006 2:25:00");
        // console.log(ApniMarziKaTime)

        // Is Tarik Ko Kon Sa Din Tha Ye Check Karne Ke Liyen Or Tarik Set Karne Ke Liyen Khod se !  

        // var d = new Date();

        // d.setDate(6)

        // console.log(d)

        // Isi Tarike Se In Sub Me Bhi Set Kar Sakte Hain Value Khud Se!

        //     METHOD                          (VARIABLE REPRESENTING THE          Result
        //                                         DATE OBJECT IS d) 

        //   setFullYear()                     d.setFullYear(2006)               Year Is 2006       
        //   setMonth()                        d.setMonth(6)                     Month Is 6 (July)
        //   setDay()                          d.setDay(6)                       Day Is 6 (Friday 2020)
        //   setHours()                        d.setHours(6)                     6 a.m.
        //   setMinutes()                      d.setMinutes(6)                   6 Minutes Past The Hour
        //   setSeconds()                      d.setSeconds(6)                   6 Seconds Past The Minute
        //   setMilliseconds()                 d.setMilliseconds(6)              6 Milliseconds Past The second
        //   setDate()                         d.setDate(6)                      Day Of Month Is 6
        //   setTime()                         d.setTime(6)                      6 Times

        // Time Check Karne Ka Easy Code Concatinate!

        // var new_Date = new Date();
        // var dateTwo = new_Date.getHours()
        // var dateThree = new_Date.getMinutes()
        // var dateForth = new_Date.getSeconds()
        // var dateFive = new_Date.getMilliseconds()
        // var mixing = " Time " + dateTwo + ":" + dateThree + ":" + dateForth + ":" + dateFive

        // console.log(mixing)

        // This Is Function

        // function PracticeByFunction(){
        //     alert("Jibran")
        // }
        // PracticeByFunction()

        // function PracticeByFunction(){
        //     var name = "Xyz Hum Function Ke under Koi Bhi KeyWord Type Kr Sakte Hain JavaScrpit Ka!"
        //     console.log(name)
        // }
        // PracticeByFunction()

        // function PracticeByFunction1(){

        // var new_Date = new Date();
        // var dateTwo = new_Date.getHours()
        // var dateThree = new_Date.getMinutes()
        // var dateForth = new_Date.getSeconds()
        // var dateFive = new_Date.getMilliseconds()
        // var mixing = " Time " + dateTwo + ":" + dateThree + ":" + dateForth + ":" + dateFive

        // console.log(mixing)

        // }

        // PracticeByFunction1()

        // This Is Local Variable Jo Ke Variable ko Funtion Ke bhar Col Nhi Kar Sakte Undifined Dedega Yani Ke Hum Ne Us Ko Defined He Nhi Kia!

        // function PracticeByFunction(){
        //     var name1 = "Xyz Hum Function Ke under Koi Bhi KeyWord Type Kr Sakte Hain JavaScrpit Ka!"

        // }
        // PracticeByFunction()
        // console.log(name1)

        // This Is Globale Variable Yani Ke Hum Esse Function Ke Under Call Kar Sakte Hain 

        // var name1 = "Xyz Hum Function Ke under Koi Bhi KeyWord Type Kr Sakte Hain JavaScrpit Ka!"
        // function PracticeByFunction(){
        //     console.log(name1)

        // }
        // PracticeByFunction()

        // function Practice (a,b){
        // console.log(a+b)
        // }
        // Practice(5,10)

        // This Is NaN Q Ke Ap Ne a ki To Value dedi mgr b ki nhi de

        // function Practice (a,b){
        // console.log(a+b)
        // }     
        // Practice(5,)

        // function Practice (a = 10,b = 10){
        // console.log(a+b)
        // }     
        // Practice()

        // function Practice (a,b = 10){
        // console.log(a+b)
        // }     
        // Practice(5,)

        // function Practice(Name){
        // alert(Name)
        // }
        // Practice("Hello Pakistan!")

        // function Practice(a,b,c){
        // alert(a+b+c)
        // }
        // Practice(10,4,32)

        // return yani ke hum kesi se value lene ke liyen use karte hain!

        // function Practice(a,b,c){
        //     var name1 = a+b+c
        //    return a
        // }
        // var b = Practice(10,4,32)
        // alert (b)//Error: name1 Is undefined
        // alert(name1)//Error: name1 Is Not Defined

        // var greet = "Hi"
        // function Practice(a,b,c){
        //     alert(greet)
        //     var name1 = a+b+c
        //    return a
        // }
        // var b = Practice(10,4,32)
        // alert (b)

        // function Practice(a, b, c, d) {
        //     return a + b + c + d
        // }
        // alert(Practice(15, 10, 5, 10))
        // alert(Practice(5, 5, 20, 10))
        // alert(Practice(4, 20, 6, 10))
        // alert(Practice(4, 20, 6, 10))

        // Basic CalCulator Application Throw Function!

        // function Calc(num1, opr, num2) {
        //     if (opr === "+") {
        //         return (+num1) + (+num2)
        //     }
        //     else if (opr === "-") {
        //         return num1 - num2
        //     }
        //     else if (opr === "*") {
        //         return num1 * num2
        //     }
        //     else if (opr === "/") {
        //         return num1 / num2
        //     }
        //     else if (opr === "%") {
        //         return num1 % num2
        //     }
        //     else {
        //         return "You Did Not Write Correct Operator!"
        //     }
        // }
        // var result = Calc(5, "+", 5)
        // var result1 = Calc(15, "-", 10)
        // var result2 = Calc(2, "*", 5)
        // var result3 = Calc(2, "/", 30)
        // var result4 = Calc(10, "%", 3)

        // console.log(result + " " + "+")
        // console.log(result1 + " " + "-")
        // console.log(result2 + " " + "*")
        // console.log(result3 + " " + "/")
        // console.log(result4 + " " + "%")

        //      Swicth Statement!

        // For Example!

        // var Day = prompt("Enter Your Day!")
        // if (Day === "Saturday" || Day === "Sunday") {
        //     alert("Maze Maze Woope Cool")
        // }
        // else if (Day === "Friday") {
        //     alert("Neki Day")
        // }

        // Esay Code From Switch Statement! Uper Wala Our Niche Wala Dono Same Code Hain But Niche Wala Easy Ha!

        //     var Day = prompt("Enter Your Day!")

        //    switch (Day){
        //        case "Sunday":
        //        alert("Maze Maze Woopee Cool")
        //        break;
        //        case "Saturday":
        //        alert("Maze Maze Woopee Cool")
        //        break;
        //        case "Friday":
        //        alert("Neki Day Bro")
        //        break;
        //        default: 
        //        alert("Shoot Me Now")
        //        break;
        //        }

        // var Brother = "Jibran";

        // switch (Brother) {
        //     case "Jibran":
        //         alert("Hello Jibran");
        //         break;
        //     case "Hayyan":
        //         alert("Hello Hayyan");
        //         break;
        //     case "Osama":
        //         alert("Hello Osama");
        //         break;
        //     case "Ali":
        //         alert("Hello Ali");
        //         break;
        //     default:
        //         alert("Ok You Are Not Correct");
        // }

        //    This Is Swicth Statement

        // while Loop & do while Loop  Start

        // For Example:
        // var i = 0;
        // for(;i<10 ; i++){
        // console.log(i)
        // }

        // Start!

        // While Loop

        // var i = 0;
        // while (i<=10 ){
        //     console.log(i)
        //     i++
        // }

        // Do While Loop

        // var i = 0;
        // do{
        //     console.log(i)
        //     i++
        // }
        // while(i<20)

        // Placing Script

        /* <script>

        // // function Greeting(params)
        // //     alert(params)
        // // }
        // // Greeting("Hello Mark")

        //  <//script> */

        /*FOR EXAMPLE THIS IS TEXT ON COMMINTING */
        //FOR EXAMPLE THIS IS TEXT ON COMMINTING //

        // Events Link, Events Button!

        // Onclick

        // function rol() {
        //     document.write('Hello User1!')
        // }
        // rol()


        // function col() {
        //     document.write('Hello User!')
        // }
        // col()

        // function  Greeting(Popup) {
        //     alert(Popup)
        // }

        // OnClick Calc Function

        // function Calc(){
        //     var num1 = prompt("Enter Your Num1 Value")
        //     var Opr = prompt("Enter Your Operator")
        //     var num2 = prompt("Enter Your Num2 Value")

        // console.log(num1+Opr+num2)

        // if(Opr === "+"){
        //  document.write((+num1)+(+num2))
        // }
        // else if(Opr === "-"){
        // document.write(num1-num2)

        // }
        // else if(Opr === "*"){
        // document.write(num1*num2)

        // }
        // else if(Opr === "/"){
        // document.write(num1/num2)

        // }
        // else if(Opr === "%"){
        // document.write(num1%num2)

        // }
        // else{
        //     document.write("You Did not Write Correct Operator!")
        // }
        // }

        // function data(){
        // var name1 = prompt("Enter Your Name")
        // document.write("Thank You" +" "+name1+" "+ "!")
        // }

        // function data() {
        //     var name2 = prompt("Enter Your Name!")
        //     document.write("Thank You" + " " + name2 + " " + "!")
        // }

        // function data1() {
        //     var name1 = prompt("Enter Your Father Name!")
        //     document.write("Thank You" + " " + name1 + " " + "!")
        // }

        // Chp = 49

// function CheckAddress(){
//     if(document.getElementById("email").value === ""){
// alert("Email Is Required!")
//     }
//      if(document.getElementById("pass").value === ""){
// alert("Password Is Required!")
//     }
//     if(document.getElementById("email").value === "" && document.getElementById("pass").value === ""){
// alert("Email & PassWord Is Required!")
//     }
// }

// function CheckAddress(check){
//     if(document.getElementById(check).value === ""){
//  alert("Email Is Required!")
//      }
// }

// Somes Coders Are write GetValue 

// function CheckAddress(fieldValue){
//     var getidValue = document.getElementById(fieldValue).value
//     if (getidValue === ""){ 
// alert('Email Is Required!')

//     }
// }

// Agr Hamein Input Ki Value Change Karni Ho To Is Tarah Karenge!

// Agr Koi Value Set Karni Hoto

// function SetValue(){
// var getUname = document.getElementById("uname")
// getUname.value = "Jibran" 
// }

// Agr Koi Value Get Karni Hoto

// function GetValue(){
//     alert("OK")
// }

// Word Ke Aski Code Maloom Karne Ka Code

// var asciCode = "Z";
// console.log(asciCode.charCodeAt())

// CalCulator Application

// function GetValue(Value){
// var result = document.getElementById("result");
// result.value += Value
// }

// function clearValue(){
//     var result = document.getElementById("result");
//     result.value = ""
// }
// function getCompleteValue(){
//     var result = document.getElementById("result")
//     result.value = eval(result.value)
// }


// InnerHTML Hum Jab Karte Hain Jab Us Tag Me Pehle Se hi Koi Text Mojood Ho OK!

// function ReadMore(){
// var new_Paragraph = document.getElementById('new_Paragraph').innerHTML

// var Paragraph = document.getElementById('Paragraph')
// Paragraph.innerHTML = new_Paragraph
// }

// function Login(){
// var Form = '<ul><h1><li>Form</li></h1><br> <li>Name: <input  type="text" placeholder="Enter Your Name" /></li><br><li>Father Name: <input type="text" placeholder="Enter Your Father Name" /></li><br><li>Roll No: <input type="text" placeholder="Enter Your Roll No" /></li><br> <li><button onclick="submit()">Submit</button></li></ul>'
// var button = document.getElementById('btn')
// button.innerHTML = Form
// }
// function submit(){
//     alert("Thank You User!")
// }

// function List(){
//     var List = '<ul><li>Name 1: Karachi</li><li>Name 2: Islamabad</li><li>Name 3: Lahore</li><li>Name 4: Hyderabad</li><li>Name 5: Iraq</li><li>Name 6: Iran</li><li>Name 7: Balochistan</li><li>Name 8: Roose</li><li>Name 9: America</li><li>Name 10: Algeria</li><li>Name 11: Albania</li><li>Name 12: Faisalabad</li><li>Name 13: Afghanistan</li><li>Name 14: Honk Kong</li><li>Name 15: Multan</li><li>Name 16: Dubai</li><li>Name 17: India</li><li>Name 18: New York</li><li>Name 19: Paris</li><li>Name 20: London</li></ul>'
//     var getPara = document.getElementById('para')
//     getPara.innerHTML = List
// }

// function ShowMore(){
// var ShowMore = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit Eaque sequi totam perferendis nesciunt dolor aspernatur adipisci, saepe impedit minima ducimus vero praesentium quo, pariatur porro autem magni, illo quibusdam? Soluta.'
// var getShowMore = document.getElementById('para1')
// getShowMore.innerHTML = ShowMore
// }
// function lessMore(){
//     var LessMore = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit '
//     var getLessMore = document.getElementById('para')
//     getLessMore.innerHTML = LessMore 
// }

// function ReadMore(){
//     var ReadMore = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit Eaque sequi totam perferendis nesciunt dolor aspernatur adipisci, saepe impedit minima ducimus vero praesentium quo, pariatur porro autem magni, illo quibusdam? Soluta.';
//     document.getElementById('para').innerHTML = ReadMore
//  }

// JavaScript Se Style Apply Karne Ke Liyen

// function img(){
//     var getImage = document.getElementById('img')
//     getImage.className = 'hidden'
// }

// function form(){
//     var getForm = document.getElementById('form')
// getForm.className = 'Form'
// }

// function input(){
//     var getInput = document.getElementById('input1')
//     getInput.className = 'input2'
// }
// function input2(){
//     var getInput = document.getElementById('input2')
//     getInput.className = 'input2'
// }
// function input3(){
//     var getInput = document.getElementById('input3')
//     getInput.className = 'input2'
// }

// Ye Jo Pichli Class Ha Na UnKo hidden Karde Ga Ye += " xyz"! 

// function ulist(){
//     var getulist = document.getElementById('ulist')
//     getulist.className += ' ulisthidden'
// }

// function changeImage(){
//     var getImage = document.getElementById('image')
//     getImage.src = 'https://img.wonderhowto.com/img/91/69/63559050599992/0/hack-windows-7-become-admin.1280x600.jpg'
// }

// function reviseImage(){
//     var getReviseImage = document.getElementById('image')
//     getReviseImage.src = '../Wallpaper/2021215.jpg'
// }

// function changeImage(){
//     document.getElementById('image').src = 'https://img.wonderhowto.com/img/91/69/63559050599992/0/hack-windows-7-become-admin.1280x600.jpg'
// }

// function reviseImage(){
//       document.getElementById('image').src = '../Wallpaper/2021215.jpg'
// }

// function changeImage(id,src){
// var getImage = document.getElementById(id)
// getImage.src = src
// }

// Link Change Kis Tarike Se Karte Hain 

// function link(){
//     document.getElementById('link').href = 'https://assignment-quiz-application.web.app'
// }

// Html Tag me JavaScript Se Styling Kese karte hain !

// function changeImage(){
//    var getImage = document.getElementById('image')
//    getImage.style.width='70%'
//    getImage.style.height='100px'
// }

// function changeImage(){
//    var getpera = document.getElementById('pera')
//    getpera.style.backgroundColor='red'
//    getpera.style.fontStyle='Oblique'
//    getpera.style.fontSize='10px'
//    getpera.style.fontWeight='bold'
// }

// Float dena Hoga To Hum cssFloat lekhe Ge JavaScript Me 

// function changeImage(){
//    var getpera = document.getElementById('pera')
//    getpera.style.backgroundColor='red'
//    getpera.style.fontStyle='Oblique'
//    getpera.style.fontSize='10px'
//    getpera.style.fontWeight='bold'
//    getpera.style.cssFloat='right'
// }

///////////////////////////////////////////////////////////////////////////////////////

// Function Kia Karta ha Bhai Wo Koi Sa Bhi Html Tag Pe Click Ho Ya Us Pe Leke Jaien Mouse to Wo Jb Us Pe Stylink Karega yani ke wo id get karke uspe jb click hoga to wo us tag pr styling kardega OK
 
// Ye Khali Unke Index Number Per Styling Karega OK! 

// Or Agr Hum Direct variable me kaam karenge to wo sb tag pe kaam karega agr hum TagName Karenge To!
// document.getElementsByTagName('p','XYZ') Ye Kia Karega bhai Html Me Jitne Bhi Tag Hote Hain Ye Sb Tag Pr Styling Kardega Ye Kia Karega Bhai get Karega Us Tag Ke Name Ko Jo Hum Iske Ander Pass Karenge Our Html Me Jitne Bhi P Ke Tag Hain Un Sab Pr Styling Apply Kardega Jo Hum Index Number Pass Karenge Us Par Styling Karde Ga OK   
 
// var getTagNamepera = document.getElementsByTagName('p')

//     getTagNamepera[3].style.backgroundColor='red'
//     getTagNamepera[3].style.color='blue'

// Ye Kia Karega Bhai Jitne Bhi Peragraph Hain Un SAb Pr Styling Apply KardeGa OK! Dono Same Kaam Karenge Ye Wala Our Niche Wala "Hard Code"!

// var getTagNamepera = document.getElementsByTagName('p')

//     getTagNamepera[0].style.backgroundColor='red'
//     getTagNamepera[0].style.color='blue'
//     getTagNamepera[1].style.backgroundColor='red'
//     getTagNamepera[1].style.color='blue'
//     getTagNamepera[2].style.backgroundColor='red'
//     getTagNamepera[2].style.color='blue'
//     getTagNamepera[3].style.backgroundColor='red'
//     getTagNamepera[3].style.color='blue'
//     getTagNamepera[4].style.backgroundColor='red'
//     getTagNamepera[4].style.color='blue'

// Ye Kia Karega Bhai Jitne Bhi Peragraph Hain Un SAb Pr Styling Apply KardeGa OK! Dono Same Kaam Karenge Ye Wala Our Upper Wala "Easy Code"!

// var getTagNamepera = document.getElementsByTagName('p')

// for(var i = 0; i< getTagNamepera.length; i++){
//     getTagNamepera[i].style.backgroundColor='red'
//     getTagNamepera[i].style.color='blue'
// }

//////////////////////////////////////////////////////////////////////////////////////////////////////////

// var getTagNamepera = document.getElementsByTagName('p')

// for(var i = 0; i< getTagNamepera.length; i++){
//       getTagNamepera[i].innerHTML = 'Chemistry Is The Branch Of Scince That Deals With The Study Of Compositions Properties & Structure Of Matter!'
// }

//////////////////////////////////////////////////////////////////////////////////////////////////////////

// Div Ke Ander Jo Paragraphh hain khali unme styling Ya Replacing Karte Hain Is Tarike Se OK!

// var getParentID = document.getElementById('Parent')
// var getTagpera = getParentID.getElementsByTagName('p')
// for(var i = 0; i < getTagpera.length; i++){
//     getTagpera[i].innerHTML = 'Chemistry Is The Branch Of Scince That Deals With The Study Of Composition Properties & Structure Of Matter!'
//     getTagpera[i].style.backgroundColor='blue'
//     getTagpera[i].style.color = 'red'
// }

// Revise!! Setting Style Chapter Se 55 Wale Chapter Se

// Input Ki Value Set Karne Ke Liyen!

// document.getElementById('inp').value = 'This Is Input'

// var getInputValue = document.getElementById('inp')
// getInputValue.value = 'This Is Input'


// function getValue(){
//     alert('Text')
// } 

// function setValue(){
// var getIdInput = document.getElementById('inp')
// getIdInput.value = 'ComFirm Input....!'
// }

// innerText Kia Karta Ha Is Me Khali Ap Text Hi Likh Sakte Hain OK
 
// function setValueInPera(){
//     var getPeraID = document.getElementById('pera')
//     getPeraID.innerText = 'Chemstry Is The Branch Of Scince That Deals With The Study Of Composition Properties & Structure Of Matter'
// }

// function cencelValueInPera(){
//     var getPeraID = document.getElementById('pera')
//     getPeraID.innerText = ""
// }

//innerHTML Se Hum Usme Koi bhi Html Ka Tag bhi Likh Sakte Hain Ok !

// function setValueInPera(){
//     var getPeraID = document.getElementById('pera')
//     getPeraID.innerHTML = '<i><b>Chemstry Is The Branch Of Scince That Deals With The Study Of Composition Properties & Structure Of Matter</b></i>' 
// }

// function cencelValueInPera(){
//     var getPeraID = document.getElementById('pera')
//     getPeraID.innerHTML = ""
// }

// function setClassName(){
//     var getImageID = document.getElementById('img')
//     getImageID.className += ' ChangeStl'
// }
// function Small(){
//     var getImageByID = document.getElementById('img')
//     getImageByID.className = 'stl'
// }

// Applicatioin Bulb ON And OFF!

// function on(){
//     var getImageID = document.getElementById('img')
//     getImageID.src = 'Bulb On Off Images.jpeg'
// }

// function off(){
//     var getImageByID = document.getElementById('img')
//     getImageByID.src = './image-asset.jpeg'
// }

////////////////////////////////////////////////////////////////////////////////////////////////////////

// Add Another Class Apply Karne Ke Liye Yani Ek Se Zyada Class Apply Karne Ke Liyen OK!

// function addClass(){
//     var getPeraID = document.getElementById('pera')
// getPeraID.className += ' Class AnotherClass'
// }

//<Li> Tag Ki Length Maloom Karne Ke Liyen!

// var className = document.getElementsByTagName('li')
// console.log(className.length)

///////////////////////////////////////////////////////////////////////////////////////////////////////////

// setIntervel(FunctionName(xyz),seconds(xyz)) kia karta ha bhai ye do value leta ha yani pheli value pochta ha Function ka name jo hum ne function bana ya hana to us ka name poch ta ha pehli value me (Function Name)!
// Our Dosri Value Me Pochta Ha Time Ke Ye Function kitne Time Baat run Hoga To Hum Usse Dosri Value Me Us Ka Time Bata te Hain jab 1000 Thusands MilliSeconds Hote Hain to Ek Second Banta Ha yani ye Function Ek Second Baat run Ho ga OK!

// var Counter = 0;
// var Intervel;

// function Timer(){
//     Counter++
// console.log('Counter : '+ " " + Counter)
// }

// Intervel = setInterval(Timer,3000)

// setTimeout(function (){
//     clearInterval(Intervel)
// },9000)

// function TimeOut(){
// console.log('Running..............')
// }
// setTimeout(TimeOut,3000)

// Add To Card Functionality

// var getImage = document.getElementById('img')
// var getName = document.getElementById('name')
// var getPrice = document.getElementById('rs')
// var getImage1 = document.getElementById('divimg')
// var getName1 = document.getElementById('divname')
// var getPrice1 = document.getElementById('divrs')
// var getbtn1 = document.getElementById('btn1')
// var div1 = document.getElementById('div')

// function addcard(){
// getImage1.src = getImage.src
// getImage1.style.width='200px'
// getImage1.style.height='200px'
// getImage1.style.marginTop='30px'

// getImage1.style.display="inline"
// getName1.innerHTML = getName.innerHTML
// getPrice1.innerHTML = getPrice.innerHTML
// getbtn1.innerHTML = 'Back Card'
// getbtn1.style.display="inline"
// }
// getbtn1.style.display="none"

// function backcard(){
//     getImage1.style.display="none"
// getPrice1.innerHTML = ""
// getName1.innerHTML = ""
// getbtn1.style.display="none"

// }

// Counter Application!

// counter = 0;

// var getCount = document.getElementById('increament&decreament')

// function increament(){
// counter++
// getCount.innerHTML = counter
// }
// function decreament(){
//     counter--
//     getCount.innerHTML = counter
// }



// function off(){
//     counter = 0
//     getCount.innerHTML = ''
//     document.getElementById('off').disabled=true
//     document.getElementById('on').disabled=false
    
// }
// function on(){
//     counter = 0
//     getCount.innerHTML = 0
//     document.getElementById('on').disabled=true
//     document.getElementById('off').disabled=false
// }


// Stop Watch Application!

// var min = 0;
// var sec = 0;
// var msec = 0;

// var getmin = document.getElementById('min');
// var getsec = document.getElementById('sec');
// var getmsec = document.getElementById('msec');
// var ulist = document.getElementById('ul')


// var Intervel;

// function Timer(){
//     msec++
//     getmsec.innerHTML = msec;
//     if(msec >= 100){
// sec++
// getsec.innerHTML = sec
// msec = 0
//   }
//   else if(sec >= 59){
//       min++
//       getmin.innerHTML = min
//       sec = 0

//   }
// }
// function active(){
// Intervel = setInterval(Timer,10)
// document.getElementById('activeID').disabled=true
// }

// function pause(){
//     clearInterval(Intervel)
//     document.getElementById('activeID').disabled=false
// }
// function reset(){
//     min = 0
//     sec = 0
//     msec = 0

// getmin.innerHTML = '00'
// getsec.innerHTML = '00'
// getmsec.innerHTML = '00'
// ulist.innerHTML = ''

// pause()

// }
   
// function lab(){
    
//     var createElement = document.createElement('li')
//     var createTextNode = document.createTextNode( min + " : " + sec + " : " + msec )
//     createElement.appendChild(createTextNode)
//     ulist.appendChild(createElement)
// }

//////////////////////////////////////////////////////////////////////////////////////////////////////////

// console.log(document.childNodes[0])  // Hamari Index File Me Kesi Chez Ka Object Maloom Karna Hoto Is Me Us Ka index Number Pass Karde Gen!

// The DOM Full Form Document For Example: File Index.html; Object For Example: Tag <xyz></xyz>; Modal For Example: Jo Hum Is Tag Me Kaam Kara Rahe Hain!

// console.log(document.childNodes[1].childNodes[0]) // yani ke 1 Html and Ab Ye Us Ke Ander Jay Ga Our 0 Index Pe Jo Bhi Hoga Wo Mujhe Console Kara Dega OK! 

// console.log(document.childNodes[1].childNodes[1]) //Ya Abhi Mujhe #text La Ke dega Wo Q Q ke Bhai childNodes[1] pe space ha Wo space Ko Text me tabdeel kar deta ha ya ke ye space ka bhi index number get kar raha ha OK #text Ye Ap Ka Jang Artifacts kehla ta ha OK !! 

// console.log(document.childNodes[1].childNodes[1]) // ab jab me Document me se space remove karta hon to body index 1 pe Aajati ha OK Yani ke #text remove hojata ha jab hum space hata dete hain to !OK 

// console.log(document.childNodes[1].childNodes[1].childNodes[0].childNodes[0]) // Yani Ke Ye Html document Ke andar jay ga Our Phir Body ke ander jay ga Phir div ke ander jay ga Phir Isko PeraGraph Milega! Me Isme #text Yani Ke Jang Artifacts ko mene remove kar diya ha Yani Ke Document Me Se Mene Space Remove Kar Diya Ha Is Wajs Se Wo Get Kar Raha Ha Tag OK!

// <!DOCTYPE html> //Hum Is Tarike Se Apna Kaam Kar Sakte Hain Jis Me Na Space Hogi Na #text Jang Artifactes honge OK!
// <html lang="en"

// ><head

// ><meta charset="UTF-8"
// ><meta name="viewport" content="width=device-width, initial-scale=1.0">
//     <title>Learning JavaScript</title
        
//         ><link rel="stylesheet" href="style.css"
        
//         ><style

// ><body

// ><div

// > <p>

//Yaa to Ap Html Minifier Karen!

/////////////////////////////////////////////////////////////////////////////////////////////////////////

// Ye Kia Karega Bhai Ye Hamein Father Ka FirstChild La Dega!
 
// var getFather = document.getElementById('Father') 
// console.log(getFather.firstChild)

// nextSibling Ye Kia Karta Ha Bhai Ye HamaroKo next Child La Ke Dede ga  

// var getFirstSonID = document.getElementById('secondChild') 
// console.log(getFirstSonID.nextSibling)

// var getFirstSonID = document.getElementById('secondChild') 
// console.log(getFirstSonID.previousSibling)

//Last Child Ye Kia Karta Ha Bhai Ye hamein Last Son Ladega Q k Father Ka lastChild Last Son Ha!

// var getFather = document.getElementById('Father') 
// console.log(getFather.lastChild)

// parentNode Ye Kia Karega Bhai Ye Hamein Father Ladega 

// var getSecondSonID  = document.getElementById('secondChild') 
// console.log(getSecondSonID.parentNode)

//Agr Apko Kisi Index Ki Value Check Karni Ha Ke Kia Wo Tag Ha Ya Jang Artificates Wo Kis Tarike Se Karte Hain nodeType Ke Zariye Karte Hain Agr console  Me 3 Aaya to Jang Artificates Ha Our Agr Console Me 1 Aaya To ye Tag Ha OK!
 
// Yani Ke Ye Tag Ha!

// var getFirstChildNodeType = document.getElementById('firstChild') 
// console.log(getFirstChildNodeType.nodeType)

//////

// Yani Ke Ye Jang Artificates Ha!

// var getFatherNodeType = document.getElementById('Father') 
// console.log(getFatherNodeType.childNodes[0].nodeType)

//////

// nodeName Kia Karta Ha Bhai Ye Hamein Us Tag Ke Ander Jo Text Likha Howa Ha Wo Deta Ha Yani Tag Ka Name Deta Ha!

 // Same Bs Jang Artificates Ka Name Dega Isma OK!

// var getFatherNodeType = document.getElementById('Father') 
// console.log(getFatherNodeType.childNodes[0].nodeName)

// Same Bs Tag Ka Name Dega OK!

// var getFirstChildNodeType = document.getElementById('firstChild') 
// console.log(getFirstChildNodeType.nodeName)

////////////////

 // Same Bs Jang Artificates Ki Value Dega Isma Yani Ke Space La dega Isme OK!

// var getFatherNodeType = document.getElementById('Father') 
// console.log(getFatherNodeType.childNodes[0].nodeValue)

 // Same Bs Tag Ki Value Dega Isma Yani Ke First Son La dega Isme OK!

//  var getFatherNodeType = document.getElementById('Father') 
// console.log(getFatherNodeType.childNodes[1].nodeValue)

//////////////////////////////////////////////////////////////////////////

    // Agr hamien Ek se Zyada Div get Karne Hoen To Is Tarike Se Karte Hain!

//  var getFatherNodeType = document.getElementById('Father') 
// console.log(getFatherNodeType.childNodes[1])


// var getFather1NodeType = document.getElementById('Father1') 
// console.log(getFather1NodeType.childNodes[1])

// var getFather2NodeType = document.getElementById('Father2') 
// console.log(getFather2NodeType.childNodes[1])


//  var getFather3NodeType = document.getElementById('Father3') 
// console.log(getFather3NodeType.childNodes[1])

///////////////////////////////////////////////////////////////////////////////////////////////////////

//Agr hamein nodeList Maloom Karni Ha to Is Tarike Se Karenge Yani Ke Hamare Div Ke Jitne Bhi Child Hain Wo Aagainge Jung Artificates bhi Our Tag Name Bhi OK!

// var getFatherChildNodes = document.getElementById('Father') 
// console.log(getFatherChildNodes.childNodes)

///////////////////////////////////////////////////////////////////////////////////////////////////////

// hasAttribute Kia Karta Ha Bhai Ye Hamari HTML me Jata ha Our Check Karta Ha Ke Hamare HTML Tag Me Koi Attribute Ha Ya Nhi Jo Hum Is Ke Under Pass Karte Hain hasAttribute Ke Function Me OK!
 
//  For Example!

// var getPera = document.getElementById('pera')
 
// if(getPera.hasAttribute('class')){
// alert('Attribute Is Available')
// }
// else{
//     alert('Attribute Is Not Available')
// }

////////////////////////////////////////////////////////////////////////////////

// getAttribute Kia Karta ha Bhai Ye Hamain Us Tag Ke Class Ki Value Lake Deta ha Jo Hum getAttribute Function Ke Ander Class Pass Karte Hain OK! 
// Ye Hamain Class Ki Value Lake Deta Ha Khali!  
 
// var getPera1 = document.getElementById('pera1')

// if(getPera1.getAttribute('class') === 'Classpera1'){
// alert('Value Is Access')
// }

// else{
//     alert('Value Is Not Access')
// }

// console.log(getPera1.getAttribute('class'))

//////////////////////////////////////////////////////////////////////////////////

// Agr Hamain Kesi Tag Ki Koi Class Ya Id deni Hoto Hum Kis Tarah Degein For Example!

// setAttribute Kia Karta ha Bhai Ye Hamare Tag Ko Koi id Deni Ho Ya Koi Class Deni Hoto Hum setAttribute Se Denge  For Example!

// var getPera2 = document.getElementById('pera2')

// getPera2.setAttribute('Class','newClass')

// console.log(getPera2.getAttribute('Class'))

//////////////////////////////////////////////////////////////////////////////////

// attributes Kia Karta Ha Bhai Ye Hamere Tag Me Jitne Bhi attributes Hain Wo Sab La deta Ha OK!
 
//   var getPera3 = document.getElementById('pera3')

//   console.log(getPera3.attributes)
  
/////////////////////////////////////////////////////////////////////////////////

// Same! Bs Loop Se Sare Element Get Karliyen Hain

// var getPera3 = document.getElementById('pera3')

// for(var i = 0; i < 3; i++){
//     console.log(getPera3.attributes[i].nodeName)
// }

///////////////////////////////////////////////////////////

// Same Bs Insab Ki Value La Dega

// var getPera3 = document.getElementById('pera3ID')

// for(var i = 0; i < 3; i++){
//     console.log(getPera3.attributes[i].nodeValue)
// }

/////////////////////////////////////////////////////////////////////////////

// Create Elements Kia Karta Ha Bhai Ye HTML Ka Tag Deta Ha Hamein Jo Hum Is Ke Function Me Tag Name Dete Hain -->
// For Example!

// var createElements = document.createElement('p')
// console.log(createElements)

// var createElements = document.createElement('h1')
// console.log(createElements)

// var createElements = document.createElement('img')
// console.log(createElements)

// var createElements = document.createElement('div')
// console.log(createElements)

///////////////////////////////////////////////////////////////////////////////

// Ye Kia Kar Raha Ha Bhai Ye Ek Tag Create Kar Raha Ha Jo Ke createElement Se Ho Raha Ha OK Is Ke Baad Ek text Create Ho Raha Ha Jo Ke createTextNode Se Ho Raha Ha Is Ke bad appendChild Kia Karta Ha Bhai ForExample Create Element Jo Horaha Ha Na Yani Ke Phele Element Create Hoga us ke bad appendChild ke Ander CreateText Node Aajay Ga  CreateElement Kia ha Bhai Ye Ek Parent Ha Our CreatTextNode Us Ka Child Ha OK! 
 
// var createElementTag = document.createElement('p') // Ye Kia Kar Raha Ha Bhai Ye Element Yani Tag Create Kar raha Ha Kis Se createElement Se OK! 
// var createTextNode = document.createTextNode("This Is Example By createTextNode And create Element And Append Child!") // Our Ye Kia Kar raha Ha Bhai Ye Text Create Kar raha Ha Kis Se createTextNode Se OK!
// var appendChild = createElementTag.appendChild(createTextNode) // Ye Kia Kar Raha Ha Bhai Ye createElement Ko Parent Bana Raha Ha Our createTextNode Ko Us Ka Child Bana Raha ha Yani Ke Peragraph Ke Ander Text Aayga OK! 
// console.log(createElementTag)

///////////////////////////////////////////////////////////////////////////////

// Hum HTML Ke Div Ke Ander H1 Ki Heading JavaScript Se Is Tarike Se Bana Te Hain div Me OK!

// var createElement = document.createElement('h1')
// var createTextNode = document.createTextNode('This Is Text')
// createElement.appendChild(createTextNode) 

// var getdiv = document.getElementById('main');
// getdiv.appendChild(createElement)

///////////////////////////////////////////////////////////////////////////////

// ToDo AppliCation!

// var getInput = document.getElementById('input');
// var getUl = document.getElementById('ul')

// function add(){

//     var createElement = document.createElement('li')
//     createElement.className = 'listyle'
//     var CreateTextNode = document.createTextNode(getInput.value)
//     createElement.appendChild(CreateTextNode)
//     getUl.appendChild(createElement)

//     var editbtn = document.createElement('button')
//     editbtn.className = 'styling'
//     editbtn.setAttribute('onmouseover','this.style.backgroundColor = "green",this.style.color="white",this.style.fontSize="17px", this.style.borderRadius="6px"')
//     editbtn.setAttribute('onmouseout',"this.style.color = 'green',this.style.backgroundColor='WHITE',this.style.borderRadius='7px'")
//     var editBtnText = document.createTextNode('EDIT')
//     editbtn.setAttribute('onclick','editbtnclick(this)')
//     editbtn.appendChild(editBtnText)
//     createElement.appendChild(editbtn)

//     var delbtn = document.createElement('button')
//     delbtn.className = 'stylingbtn'
//     delbtn.setAttribute('onmouseover','this.style.backgroundColor = "red",this.style.color="white",this.style.fontSize="17px", this.style.borderRadius="6px"')
//     delbtn.setAttribute('onmouseout',"this.style.color = 'red',this.style.backgroundColor='WHITE',this.style.borderRadius='7px'")

//     delbtn.setAttribute('onclick','del(this)')       
//     var delText = document.createTextNode('DELETE')
//     delbtn.appendChild(delText)
//     createElement.appendChild(delbtn)

//     getInput.value = ''
// }
// function closee(){
// getInput.value = ''
// }

// function deleteAll(){
//     getUl.innerHTML = ""
// }

// function del(Val){
// Val.parentNode.remove()
// }
// function editbtnclick(editbtnclick){
//     var getValue = prompt('Enter Your EDIT Value',editbtnclick.parentNode.childNodes[0].nodeValue) 
//     editbtnclick.parentNode.childNodes[0].nodeValue = getValue
// }    

/////////////////////////////////////////////////////////////////////////////

// Starting With Object //

//  This Is The Main Structure Of Object! //

// var User = {
//   !This Is ProPerty <= | Name : 'Mark', // => This Is Value!
//   !This Is ProPerty <= | Father_Name : 'Ace', // => This Is Value!
//   !This Is ProPerty <= | Age : '18' , // => This Is Value!
//   !This Is ProPerty <= | Number : 054654645657, // => This Is Value!
//   !This Is ProPerty <= | Roll_Number: 1875, // => This Is Value!
//   !This Is ProPerty <= | Gmail_Address: 'mark@gmail.com' // => This Is Value!
// } 
// console.log(User)

/////////////////////////////////////////////////////////////////////////////

// Multiple Object Bana ne Hain To Ap Is Tarike Se Banayenge For Example:

// var User1 = {
//     Name : 'User1',
//     Father_Name : 'User1',
//     Age : '32' ,
//     Number : 030654645657,
//     Roll_Number: 1876,
//     Gmail_Address: 'User1@gmail.com'
// }

// var User2 = {
//     Name : 'User2',
//     Father_Name : 'User2',
//     Age : '54' ,
//     Number : 031654645657,
//     Roll_Number: 1877,
//     Gmail_Address: 'User2@gmail.com'
// }

// var User3 = {
//     Name : 'User3',
//     Father_Name : 'User3',
//     Age : '15' ,
//     Number : 034656665657,
//     Roll_Number: 1878,
//     Gmail_Address: 'User3@gmail.com'
// }

// var User4 = {
//     Name : 'User4',
//     Father_Name : 'User4',
//     Age : '13' ,
//     Number : 033654645657,
//     Roll_Number: 1879,
//     Gmail_Address: 'User4@gmail.com'
// }

// var User5 = {
//     Name : 'User5',
//     Father_Name : 'User5',
//     Age : '19' ,
//     Number : 032654645657,
//     Roll_Number: 1880,
//     Gmail_Address: 'User5@gmail.com'
// }

// var User6 = {
//     Name : 'User6',
//     Father_Name : 'User6',
//     Age : '16' ,
//     Number : 03654645657,
//     Roll_Number: 1881,
//     Gmail_Address: 'User6@gmail.com'
// }

// var User7 = {
//     Name : 'User7',
//     Father_Name : 'User7',
//     Age : '17' ,
//     Number : 037654645657,
//     Roll_Number: 1882,
//     Gmail_Address: 'User7@gmail.com'
// }

// var User8 = {
//     Name : 'User8',
//     Father_Name : 'User8',
//     Age : '21',
//     Number : 030654645657,
//     Roll_Number: 1883,
//     Gmail_Address: 'User8@gmail.com'
// }

// var User9 = {
//     Name : 'User9',
//     Father_Name : 'User9',
//     Age : '30' ,
//     Number : 032154645656,
//     Roll_Number: 1885,
//     Gmail_Address: 'User9@gmail.com'
// }
// var User10 = {
//     Name : 'User10',
//     Father_Name : 'User10',
//     Age : '17' ,
//     Number : 034654645657,
//     Roll_Number: 1885,
//     Gmail_Address: 'User@gmail.com'
// }

// console.log(User1);
// console.log(User2);
// console.log(User3);
// console.log(User4);
// console.log(User5);
// console.log(User6);
// console.log(User7);
// console.log(User8);
// console.log(User9);
// console.log(User10);

////////////////////////////////////////////////////////////////////////////

//Array Hamesha Object Hi return Karta Ha OK! Solve Question:

// For Example:

// var UserArray = ['Mark','Ace','Tom'];

// var UserObject = {
//     0 : 'Mark',
//     1 : 'Ace',
//     2 : 'Tom',
// };

// console.log(UserArray)
// console.log(UserObject)

//////////////////////////////////////////////////////////////////////////////

// Agr Hamein Object Ke Ander Koi Value Add Karani Hoto Kese Karayenge For Example!

// var User = {
//              Name : 'Mark', // => This Is Value!
//              Father_Name : 'Ace', // => This Is Value!
//              Age : '18' , // => This Is Value!
//              Number : 054654645657, // => This Is Value!
//              Roll_Number: 1875, // => This Is Value!
//              Gmail_Address: 'mark@gmail.com' // => This Is Value!
//        } 
// console.log(User)

// User.Facebook_ID = 'Xtylish Mark'
 
//////////////////////////////////////////////////////////////////////////////

// Object Ke Ander Hum Array Bhi Bana Sakte Hain!

// var User = {
//              Name : 'Mark', // => This Is Value!
//              Father_Name : 'Ace', // => This Is Value!
//              Age : '18' , // => This Is Value!
//              Number : 054654645657, // => This Is Value!
//              Roll_Number: 1875, // => This Is Value!
//              Gmail_Address: 'mark@gmail.com' // => This Is Value!
//        } 
// console.log(User)

// User.Facebook_IDS = ["Xtylish Mark","Ace Prince","Khano Ka Khan"]

/////////////////////////////////////////////////////////////////////////////

// Jis Tarike Se Hum Object Me String Value Add Karta Hain isi Tarike Se Hum Object Me Numbers Array True False Condition Bhi Pas Kar Sakte Hain OK! For Example!

// var User = {
//              Name : 'Mark', // => This Is Value!
//              Father_Name : 'Ace', // => This Is Value!
//              Age : '18' , // => This Is Value!
//              Number : 054654645657, // => This Is Value!
//              Roll_Number: 1875, // => This Is Value!
//              Gmail_Address: 'mark@gmail.com' // => This Is Value!
//        } 
// console.log(User)

// User.Property = 'Value'; // String Value Added By Object!
// User.Property0 = ['Value','Value1','Value2']; // Array Value Added By Object!
// User.Property1 = 1832 ; // Numbers Value Added By Object!
// User.Property2 = 1.9143445234 ; // Numbers Value Added By Object!
// User.Property3 = 2+2 ; // Bodmas Rule Value Added By Object!
// User.Property4 = true // false; // True And False Condition!
// User.Property5 = {} // Hum Amti Object Bhi Add Kara Sakte Hain Amti Array Bhi Add Kara Sakte Hain OK!
// User.Property6 = undefined // Hum Undefined bhi Object Me Add Kara Sakte Hain OK!             
// User.Property7 = null // Hum null bhi Object Me Add Kara Sakte Hain OK!             

// Hum Ek Amti Object Bhi Bana Sakte Hain Variable Me For Example:
// Our emti Object Ke Ander Hum Koi Property Bhi Add Kara Sakte Hain Ok

// var emtiObj = {};

// console.log(emtiObj)

// emtiObj.Property = 'emti Object'

// Object Ke Ander Hum Array Bhi Bana Sakte Hain Our Array Ke Ander Hum Object Bhi Bana Sakte Hain OK!
// Object Ke Ander Ap Ek Value Ko Dosri Value Se Replace Bhi Kara Sakte Ho OK!

////////////////////////////////////////////////////////////////////////////// 

// isme kia kar raha hon Bhai Me Me Check Kar Raha Hon Ke Property Exit Karti Ha Ya Nhi Emti Object Me Jo Ke Mene Ek Object Bana Ya Ha OK!
 
// var emtiObj = {};

// console.log(emtiObj)

// emtiObj.Property = 'emti Object'

// var propertyExit = 'Property' in emtiObj;

// console.log(propertyExit)

////////////////////////////////////////////////////////////////////////////////

// Agr Hamein Apne Object Me Se Kesi Property Ko remove Karana Hoto Kese Karaynge For Example!

// var emtiObj = {};

// console.log(emtiObj)

// emtiObj.Property = 'emti Object'

// var deleteProperty = delete emtiObj.Property;
// console.log(deleteProperty)

// var propertyExit = 'Property' in emtiObj;

// console.log(propertyExit)

/////////////////////////////////////////////////////////////////////////////

// Basic Quiz AppliCation By Object!

// var Quiz = [
//     {
//         Q1: 'Whats Your Name?',
//         Ans: {
//         1: "Mark",
//         2: "Ace",
//         3: "Joker",
//         CorrectAns: '2'
//         }
//     },
//     {
//         Q2: 'Whats Your Age?',
//         Ans: {
//         a: "18",
//         b: "15",
//         c: "12",
//         CorrectAns: 'c'
//         }
//     },
//     {
//         Q3: 'Whats Your Number?',
//         Ans: {
//         1: "+923321323",
//         2: "+933442342",
//         3: "+919343849",
//         CorrectAns: '1'
//         }
//     },
// ]

// console.log(Quiz)

//////////////////////////////////////////////////////////////////////////

//Function Method kia Hota Ha Bhai Function Method Hota Ya Ha Ka Jis Ke Ander Objec Use Ho Wo Kehla Ta Ha Function Method

// Constructure Function Kia Hota Ha Bhai For Example!
// This Is Contructure Function OK!
// Ya Bhi As A Object Hi Generete Karta Ha OK!

// function Students(s1,s2,s3,s4,s5){ // => Function Ka Shuru Ka Name Ka Word Capital Hi Hona Chaiyen Warna Wo Error Dedeg OK! 
//     this.A = s1; // This Yani jahan Hum Khare Howe We Hain A Yani Ke Property = Deke Us Property Ki Value Dedi Ok Joke Hum Ne Parameter Me Diwi Thi Our Jahan Hum Function Ko Call Karenge Wahan Hum Us Property Ki Value Denge Real Wali OK!
//     this.B = s2; // This Yani jahan Hum Khare Howe We Hain B Yani Ke Property = Deke Us Property Ki Value Dedi Ok Joke Hum Ne Parameter Me Diwi Thi Our Jahan Hum Function Ko Call Karenge Wahan Hum Us Property Ki Value Denge Real Wali OK!
//     this.C = s3; // This Yani jahan Hum Khare Howe We Hain C Yani Ke Property = Deke Us Property Ki Value Dedi Ok Joke Hum Ne Parameter Me Diwi Thi Our Jahan Hum Function Ko Call Karenge Wahan Hum Us Property Ki Value Denge Real Wali OK!
//     this.D = s4; // This Yani jahan Hum Khare Howe We Hain D Yani Ke Property = Deke Us Property Ki Value Dedi Ok Joke Hum Ne Parameter Me Diwi Thi Our Jahan Hum Function Ko Call Karenge Wahan Hum Us Property Ki Value Denge Real Wali OK!
//     this.E = s5; // This Yani jahan Hum Khare Howe We Hain E Yani Ke Property = Deke Us Property Ki Value Dedi Ok Joke Hum Ne Parameter Me Diwi Thi Our Jahan Hum Function Ko Call Karenge Wahan Hum Us Property Ki Value Denge Real Wali OK!
// }
// var Xyz = new Students('Mark','Ace','Cas','Shas','Bilal') // Is Chizz Ko Hum Instance Pass Karna Kehte Hain Yani Ke Object Bana Na Kehte Hain OK! new As A Key Word Ha JavaScript Ka OK Our Hum Yahan Pr Function Call Kar Raha Hain Studente Wala Yani Ke Ab Hum Is Function Ke Ander Real Value Denge Property Ki OK! 
// console.log(Xyz)

//////////////////////////////////////////////////////////////////////////////
// Agr Hamein Student Ka data Bana Na Hoto To Hum Kis Tarike Se Banate Hain This Is Long Code!

// var obj ={
//     name : 'Mark',
//     roll: 1922
// }
// var obj ={
//     name : 'Mark',
//     roll: 1922
// }
// var obj ={
//     name : 'Mark',
//     roll: 1922
// }

///////////////////////////////////////////////////////////////////////////

// Constructure Fuction me Hamein Code Likhne Me Aasani Hoti Ha Yani Ke Agr Hamein Student Ka Deta Bana Na Hoto Hum Bar Bar Function Baneyinge Kia Is Ka Solve Constructure Function Karta Ha OK!
 
// function Students(name,roll){
// this.name = name;
// this.roll = roll;
// }
// console.log(new Students('Mark',1878))
// console.log(new Students('Ace',1823))
// console.log(new Students('Bilal',1254))
// console.log(new Students('desb',1943))
// console.log(new Students('Shad',1345))

//////////////////////////////////////////////////////////////////////////////

// Constructure Fuction me Ham normal Function Bhi Bana Sakte Hain OK For Example!

// function Students(name,roll){
// this.name = name;
// this.roll = roll;
// this.CalCulateAnnual = function CalCulateAnnuale(Father_Name,Age){
//     this.Father_Name = Father_Name,
//     this.Age = Age
// }
// }
// console.log(new Students('Mark',1878))

//////////////////////////////////////////////////////////////////////////////

// Constructure Function Ke Aander Bhi Hum As a Normal Function Bana Sakte Hain For Example:

// function Student(Name,Roll_No){
//       this.FullName = Name;
//       this.Roll_Number = Roll_No;
//       this.FunctionInCons = function(){
//           return this.FullName
//       }
// }
// var getValue = new Student('Myers',1458)
// console.log(getValue) 
// console.log(getValue.FunctionInCons())

///////////////////////////////////////////////////////////////////////////////

// Ye Kia Kar raha Ha Bhai Ye Bar Bar Ek User Create Kar Raha Ha Our Us Me Bar Bar Ek Function Bana Raha Ha Alag a Hum cha Raha Hain Ke Function Ki Copy Ban Jay Our Jab Hamein Cheiyen Hoto Jab Hum Us Copy Ko Paste Karden Wo Kese Karenge For Example! 

// function Student(Name,Roll_No){
//       this.FullName = Name;
//       this.Roll_Number = Roll_No;
//       this.FunctionInCons = function(){
//           return this.FullName
//       }
// }
// var getValue = new Student('Myers',1451)
// var getValue1 = new Student('Mark',1452)
// var getValue2 = new Student('Ace',1453)
// var getValue3 = new Student('Miles',1454)
// var getValue4 = new Student('Grow',1455)

// console.log(getValue)
// console.log(getValue1)
// console.log(getValue2)
// console.log(getValue3)
// console.log(getValue4) 

// console.log(getValue.FunctionInCons())

//////////////////////////////////////////////////////////////////////////////

// Prototype Kia Karta Ha Bhai Ye Function Ko Bar Bar Nhi Lata Bs UsKi Copy Karke Proto Me Rakh Deta Ha OK For Example !!. 

// function Student(Name,Roll_No){
//       this.FullName = Name;
//       this.Roll_Number = Roll_No;
// }

// Student.prototype.FunctionInCons = function(){ // Ye Kia Karega Bhai Ye Is Function Ko Proto Ke Aander Save Kardega OK!
//           return this.FullName
//       }

// var getValue = new Student('Myers',1451)
// var getValue1 = new Student('Mark',1452)
// var getValue2 = new Student('Ace',1453)
// var getValue3 = new Student('Miles',1454)
// var getValue4 = new Student('Grow',1455)

// console.log(getValue)
// console.log(getValue1)
// console.log(getValue2)
// console.log(getValue3)
// console.log(getValue4) 

// console.log(getValue.FunctionInCons())

//////////////////////////////////////////////////////////////////////////////

// Same Work: Ab Zarori Nhi Ha Ke Hum Proto Ke Aander Function Hi Save Karwyen Hum Koi Property Bhi Save Karwa Sakte Hain OK For Example:!
// For Example Hamare Pas Ek Property Ha School Ki Ab Hamein Pata Ha Ke Ye Property Sab Student Ke Aander Aaygi To Hum Is Property Ko Bhi Proto Ke Aander Save Karwa Sakte Hain OK For Example:!

// function Student(Name,Roll_No){
//       this.FullName = Name;
//       this.Roll_Number = Roll_No;
// }

// Student.prototype.School = 'Saylani'; // Ye Kia Karega Bhai Ye Is Property Ko Proto Ke Aander Save Kardega OK!

// var getValue = new Student('Myers',1451)
// var getValue1 = new Student('Mark',1452)
// var getValue2 = new Student('Ace',1453)
// var getValue3 = new Student('Miles',1454)
// var getValue4 = new Student('Grow',1455)

// console.log(getValue)
// console.log(getValue1)
// console.log(getValue2)
// console.log(getValue3)
// console.log(getValue4) 

///////////////////////////////////////////////////////////////////////////////

// // Agr Hamaroko Kesi Object Ki Properties Maloom Karni Hoto To Kis Tarike Se Karte Hain For Example!

// var Student = {
//     Name : 'Myers',
//     Father_Name : 'Ace',
//     Age : '17' ,
//     Number : 034654645657,
//     Roll_Number: 1885,
//     Gmail_Address: 'Myers@gmail.com'
// }

// for(var UserData in Student){ // Mene Kara Ye Ke Student Ki Jitni Bhi Properties Hain Wo Sab varible Me Daldo Jo Mene Variable Bana Ya Ha OK!
// console.log(UserData)
// }

//////////////////////////////////////////////////////////////////////////////

// Agr Hamaroko Kesi Object Ki Properties Ki Values Maloom Karni Hoto To Kis Tarike Se Karte Hain For Example!

// var Student = {
//     Name : 'Myers',
//     Father_Name : 'Ace',
//     Age : '17' ,
//     Number : 034654645657,
//     Roll_Number: 1885,
//     Gmail_Address: 'Myers@gmail.com'
// }

// for(var PropertiesKivalues in Student){ // Mene Kara Ye Ke Student Ki Jitni Bhi Properties Ki Values Hain Wo Sab varible Me Daldo Jo Mene Variable Bana Ya Ha OK!
// console.log(Student[PropertiesKivalues])
// }

//////////////////////////////////////////////////////////////////////////////

// Agr Hamaroko Kesi Object Ki Properties Our Values Maloom Karni Hoto To Kis Tarike Se Karte Hain For Example!

// var Student = {
//     Name : 'Myers',
//     Father_Name : 'Ace',
//     Age : '17' ,
//     Number : 034654645657,
//     Roll_Number: 1885,
//     Gmail_Address: 'Myers@gmail.com'
// }

// for(var PropertiesOurvalues in Student){ // Mene Kara Ye Ke Student Ki Jitni Bhi Properties Our Values Hain Wo Sab varible Me Daldo Jo Mene Variable Bana Ya Ha OK!
// console.log(PropertiesOurvalues,Student[PropertiesKivalues])
// }

//////////////////////////////////////////////////////////////////////////////

// in ka keyword kia karta ha bhai ye check karta ha ke Object Ke Ye Wali property ha ya nhi jo ham property Pouch te hain OK For Example!
// in Ke Keyword Ke Aander hum object ki apni property bhi maloom kar sakte hain our jo properties hum ne di hain objkect me hum dono properties maloom kar sakte hain Yani Ke Object Ki Apni Properties Bhi Our Jo Properties Hum Ne Di Hain Wo Properties Bhi Maloom Kar Sakte Hain OK For Example:!

// var Student = {
//     Name : 'Myers',
//     Father_Name : 'Ace',
//     Age : '17' ,
//     Number : 034654645657,
//     Roll_Number: 1885,
//     Gmail_Address: 'Myers@gmail.com'
// }

// console.log(Student)
// console.log('constructor' in Student) // in Ka Keyword Se Ham Object Ki Apni Properties Bhi Check Kar Sakte Hain OK! 

///////////////////////////////////////////////////////////////////////////////

// hasOwnProperty Bhi Same Kaam Karta Ha Bs Wo Object Ke Apni Properties Ko Access Nhi Karta Object Me Jo Hum Ne Property Di Hain Khali Woi Properties Check Karta Ha ke Ha Ya Nhi OK For Example:!

// var Student = {
//     Name : 'Myers',
//     Father_Name : 'Ace',
//     Age : '17' ,
//     Number : 034654645657,
//     Roll_Number: 1885,
//     Gmail_Address: 'Myers@gmail.com'
// }

// console.log(Student)
// console.log(Student.hasOwnProperty('Gmail_Address')) // hasOwnProperty Ke Keyword Se Ham Object Ki Properties Ko Hi Check Kar Sakte Hain Jo Hum Ne Di Ha Object Me OK! 

//////////////////////////////////////////////////////////////////////////////

// Revising By Object In Covered Full Object!

// OBJECT BY JAVASCRIPT!

// Syntax By OBJECT!

// var obj = {

// }
// console.log(obj)

// ///////////////////////////////////////////////////////////

// var UserObj = {
//   // This Is Property
//   name: 'Mark', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'Mark@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'Mark Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }

// console.log(UserObj)

// Array Hamesha Object Q return Karta ha!

// var UserArray = ['Mark', 1878, 'Mark@gmail.com', 03111111112, 'Mark Abdul Ace', 12]

// console.log(UserArray)

// /////////////////////////////////////////////////////////////

// Multiples Object!

// var User = {
//   // This Is Property
//   name: 'User', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User1 = {
//   // This Is Property
//   name: 'User1', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User1@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User1 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User2 = {
//   // This Is Property
//   name: 'User2', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User2@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User2 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User3 = {
//   // This Is Property
//   name: 'User3', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User3@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User3 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User4 = {
//   // This Is Property
//   name: 'User4', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User4@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User4 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User5 = {
//   // This Is Property
//   name: 'User5', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User5@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User5 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User6 = {
//   // This Is Property
//   name: 'User6', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User6@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User6 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User7 = {
//   // This Is Property
//   name: 'User7', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User7@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User7 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User8 = {
//   // This Is Property
//   name: 'User8', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User8@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User8 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User9 = {
//   // This Is Property
//   name: 'User9', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User9@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User9 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// var User10 = {
//   // This Is Property
//   name: 'User10', // => This Is Value!
//   Roll_Number: '1878', // =>  This Is Value!
//   Gmail_ID: 'User10@gmail.com', // => This Is Value!
//   Number: 03112323213, // => This Is Value!
//   Facebook_ID: 'User10 Abdul Ace', // => This Is Value!
//   Age: 12, // => This Is Value!
// }
// console.log(User)
// console.log(User1)
// console.log(User2)
// console.log(User3)
// console.log(User4)
// console.log(User5)
// console.log(User6)
// console.log(User7)
// console.log(User8)
// console.log(User9)
// console.log(User10)

// /////////////////////////////////////////////////////////

// Agr Apko Object Ke Ander Koi Property Add Karani Ha To Is Tarike Se Add Karate Hain OK!

// var User = {

// }

// User.Name = 'User';
// User.Roll_No = 1923;

// console.log(User)

// /////////////////////////////////////////////////////////

// Acha Zaroori Nhi Ke Object Ke Ander Hum String Value Pass Karen Hum Array bhi Add Karra Sakte Hain For Example!:

// var User = {

// }

// User.String_Value = 'User'; // Hum Object Ke Ander "XYZ" Value Bhi Add Kara Sakte Hain Ya De Sakte Hain OK
// User.Numbers_Value = +92343312342;
// User.Array_Value = ['Xtylish User', 'Prince User', 'Jogarii User'];
// User.Undefined_Value = undefined;
// User.MultipliCation_Value = 8 + 3;
// User.null_Value = null;
// User.Point_Value = 1.2343434344;
// User.Emtey_Object = {};
// User.True_False_Condition = true;

// console.log(User)

// /////////////////////////////////////////////////

// Practice By Object!

// var Hosting_Plans = [
//   {
//     Basic: {
//       Monthly: '$3.99',
//       Disk_Space: '100 GB',
//       Data_Transfer: '1000 GB/Mo',
//       Site_Pages: 10
//     },

//     Professional: {
//       Monthly: '$5.99',
//       Disk_Space: '500 GB',
//       Data_Transfer: '5000 GB/Mo',
//       Site_Pages: 50
//     },

//     Ultimate: {
//       Monthly: '$9.99',
//       Disk_Space: '2000 GB',
//       Data_Transfer: '20000 GB/Mo',
//       Site_Pages: 500
//     }
//   }
// ]

// console.log(Hosting_Plans)

//////////////////////////////////////////////////////

// Assignment By First Chapter In Object!

// var Cars_Detail = [
//   {
// Corola : {
//   BackGround_Color: 'Grey',
//   Tires: 4,
//   Price:  '12.35 Lakh',
//   Gear_Box: '5 Speed',
//   Launched : 2014,
//   Corola: '300 GT',
//   Engine_Displacement_cc: 1794, 
//   Fuel_Type: 'Petrol',
// },

// Civic : {
//   BackGround_Color: 'black',
//   Tires: 4,
//   Price: 50000,
//   Model: 'New',
//   Launched : 1966,
//   Civic: '350 GT'
// },

// Ferrari : {
//   BackGround_Color: 'Red',
//   Tires: 4,
//   Price: 50000,
//   Model: 'F8 Tributo',
//   Launched : 2020,
//   Lamborghini: '400 GT'
// },

// Lamborghini : {
//   BackGround_Color: 'Yellow',
//   Tires: 4,
//   Price: 50000,
//   Model: 'Lineup',
//   Launched : 1966,
//   Lamborghini: '400 GT'
// },

// Audi : {
//   Fuel_Type: 'Petrol',
//   BackGround_Color: 'Green',
//   Gear_Box: '7 Speed',
//   Recommended_Tyres:	'A3',
//   Tires: 4,
//   Price: 50300

// }
//   }
// ]
// document.write(Cars_Detail)

/////////////////////////////////////////////////////

// Quiz AppliCation By OBJECT!

// var Quiz_AppliCation = [
  
//   {
//     Quistion_NO_1: "Whats Your Name?",
//     Answer: {
//       A : "Mark",
//       B : "Mass",
//       C : "Myers",
//       Correct_Answer: 'A'
//     }
//   },
//   { 
//     Quistion_NO_2: "Whats Your Roll Number?",
//     Answer: {
//       A : 1878,
//       B : 1876,
//       C : 1877,
//       Correct_Answer: 'C'
//     }
//   },
//   { 
//     Quistion_NO_3: "Whats Your Father Name?",
//     Answer: {
//       A : "Mark",
//       B : "Mass",
//       C : "Myers",
//       Correct_Answer: 'C'
//     }
//   },
//     { 
//     Quistion_NO_4: "Whats Your Age?",
//     Answer: {
//       A : 18,
//       B : 17,
//       C : 16,
//       Correct_Answer: 'B'
//     }
//   },
//   { 
//     Quistion_NO_5: "Whats Your Number?",
//     Answer: {
//       A : 03321213123,
//       B : 03231313434,
//       C : 03432423423,
//       Correct_Answer: 'A'
//     }
//   },
//     { 
//     Quistion_NO_6: "Whats Your Gmail ID?",
//     Answer: {
//       A : "Myers34@gmail.com",
//       B : "Mark124@gmail.com",
//       C : "Mass563@gmail.com",
//       Correct_Answer: 'B'
//     }
//   },
//   {
//     Quistion_NO_7: "Whats Your Address?",
//     Answer: {
//       A : "5st Kaassic Gali Goa Khan",
//       B : "Gali Sort Fail Road",
//       C : "Market North Red Marthi Gali",
//       Correct_Answer: 'C'
//     }
//    },
//     { 
//     Quistion_NO_8: "Whats Your Favourate Hobby?",
//     Answer: {
//       A : 'Songs',
//       B : 'Games',
//       C : 'Criket',
//       Correct_Answer: 'B'
//     }
//      },
//     { 
//     Quistion_NO_9: "Whats Your Country?",
//     Answer: {
//       A : "Pakistan",
//       B : "London",
//       C : "American",
//       Correct_Answer: 'A'
//     }
//   },
//     { 
//     Quistion_NO_10: "Whats Your City?",
//     Answer: {
//       A : "Karachi",
//       B : "Hyderabad",
//       C : "Thatta",
//       Correct_Answer: 'A'
//     }
//   }
// ]
// console.log(Quiz_AppliCation)

///////////////////////////////////////////////////////////////////////////////////////////////////////////
 
// Agr Hamein Kesi Object Mese Koi Property Ko Check Karna Ha Ke Wo Property Ha Ya Nhi Ye Kese Check Karte Hain For Example:

// var User = {
//   Name: "Mark",
//   Roll_Number: 1878 
// }
// console.log(User)

// var Check_Property_True_False = "Roll_Number" in User
// console.log(Check_Property_True_False)

///////////////////////////////////////////////////////////////////////////////////////////////////////////

// Agr Ek Property Ko Delete Karna Ha To Wo I tarike Se Karte Hain Object Me For Example:

// var User = {
//   Name: "Mark",
//   Roll_Number: 1878 
// }
// var PropertyDelete = delete User.Roll_Number;
// console.log(User)
// console.log(PropertyDelete)

////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Agr Kesi Property Ko Update Karwana Hoto Kese Karwaeyn For Example!

// var User = {
//   Name: "Mark",
//   Roll_Number: 1878,
//   Gmail_ID: 'User@gmail.com'
// }
// User.Gmail_ID = "Mark321@gmail.com"
// console.log(User)

////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Jis Function Method Ke Aander OBJECT Use Ho To Wo Kehlata Ha OBJECT Method!  
// This Is Constructor Function Agr Start Ka Word Capital Hoga To Wo Constructure Function KehlayGa OK Our Agr Start Ka Word Small Hoga To Wo Normal Function Kehlay Ga OK!

// function User(name,roll_no,age){
//   this.name = name;
//   this.roll_no = roll_no;
//   this.age = age;
// }

// console.log(new User('Mark',1879,17)) //new Yani Ke Ye Value Ko Update Kar raha ha OK! 

// This Is Normal Function!

// function xyz(){

// }

///////////////////////////////////////////////////////////////////////////////////////////////////////////

// Next Constructor Function Example!
// Ye Hamaro Ko Bar Bar Object Bana Ne Se Rocta Ha!
// Our Value Same return Karta Ha Jo Value Object Deta Ha OK!

// Hard Code!

// var User = {
//   name: 'Mark',
//   roll_no: 1867
// }

// var User1 = {
//   name: 'Ace',
//   roll_no: 1877
// }

// console.log(User)
// console.log(User1)

///////////////////////////////////////////////////////////////////////////////////////////////////////////

// Same Example! But This Example Code Is Easy!
// Bar Bar OBJECT Bana Se Acha Ap Ek Hi Bar Constructor Function Bana Len Is Se Khali Console Karen Our Object Khod Hi Ban Jay Ga OK EOR EXAMPLE! 

// function User(name,roll_no){
// this.name = name;
// this. roll_no = roll_no;
// }

// var Property = new User('Mark',1876);
// var Property1 = new User('Ace',1866);
// var Property2 = new User('Myers',1879);
// var Property3 = new User('Killer',1883);
// var Property4 = new User('Rock',1896);

// console.log(Property)
// console.log(Property1)
// console.log(Property2)
// console.log(Property3)
// console.log(Property4)

///////////////////////////////////////////////////////////////////////////////////////////////////////////

// Acha Constructor Function Me Bhi Hum Value Ke Bajay Hum Function bhi De Sakte Hain For Example:

// function User(name,roll_no,gmail_id,Age){
//   this.Full_Name = name;
//   this.roll_no = roll_no;
//   this.gmail_id = gmail_id;
//   this.Age = Age;
//   this.NextFunction = function(){
//   return this.Full_Name;  
//   }
// }
// var UserDetailed = new User('Mark',1877,'mark@gmail.com',18)
// console.log(UserDetailed.NextFunction())

//////////////////////////////////////////////////////////////////////////////////////////////////////////
// Same Example!

// function User(name,age,roll,number){
//   this.FullName = name;
//   this.Age = age;
//   this.Roll_No = roll;
//   this.Numbers = number;
//   this.CalCannual = function(){
//     return this.FullName; 
//   }
// }

// var getValue = new User('Mark',17,1878,03111111110)
// var getValue1 = new User('Ace',17,1878,03111111110)
// var getValue2 = new User('Joker',17,1878,03111111110)
// var getValue3 = new User('Myers',17,1878,03111111110)
// var getValue4 = new User('Bilal',17,1878,03111111110)
// var getValue5 = new User('Hamza',17,1878,03111111110)
// var getValue6 = new User('Rehman',17,1878,03111111110)
// var getValue7 = new User('Khan',17,1878,03111111110)

// console.log(getValue.CalCannual())

//////////////////////////////////////////////////////////////////////////////////

// Prototype Kia Karta Ha Bhai Ye Jab Hum Console Kara Te Hain New User Ko To Ye Har User Me Ek Function Generete Karta Ha Agr Hume Wo Function Ko Har User Me Generete Nhi Karana To Is Ke Liyen hamaroko Ek KeyWord Mila Ha Java Script Ka Ye Har User Me Function Nhi Bana Ta For Example:
// Ye Kia Karta Ha Bhai Ye Prototype Ke Ander Rakh Deta Ha!


// function User(name,age,roll,number){
//   this.FullName = name;
//   this.Age = age;
//   this.Roll_No = roll;
//   this.Numbers = number;
// }

// User.prototype.CalCannual = function (){
//   return this.FullName; 
// }

// var User1 = new User('Mark',17,1878,03111111110)
// console.log(User1)
// var User2 = new User('Ace',19,1899,03143432315)
// console.log(User2)

/////////////////////////////////////////////////////////////////////////////////

// Second Example By Prototype In Properties!
// Ye Kia Karta Ha Bhai Ye Prototype Ke Ander Rakh Deta Ha Property OK !

// function User(name,age,roll,number){
//   this.FullName = name;
//   this.Age = age;
//   this.Roll_No = roll;
//   this.Numbers = number;
// }

// User.prototype.School = 'Saylani'

// var User1 = new User('Mark',17,1878,03111111110)
// console.log(User1)
// var User2 = new User('Ace',19,1899,03143432315)
// console.log(User2)

//////////////////////////////////////////////////////////////////////////////////

// For Example Hamein Object Ke Ander Properties Ki Length Our Properties Maloom Karni Ha Ke Object Me Kitni Properties Hain To Wo Kese Check Karte Hain For Example:

// var whatLength = {
//   Name: 'Mark',
//   Father_Name: 'Myers',
//   Roll_No: 1879,
//   School: 'Sylani',
//   Age: 18,
//   Number: 03333333122,
//   Gmail_ID: 'mark321@gmail.com'
// }

// for(var prop in whatLength) { // Isme Ho Kia Raha Ha Bhai Is Ma Ek Loop Chal Raha Ha Our Us Loop Me Ek Variable Ban Raha Ha Our Us Ka Hum Name De Rahe Hain Our Phir Hum Check Kar Raha Hain Ke Object Ki Kitni Properties Hain Our Kon Kon Si Hain Hum Name Denge Our Phir Hum in Ka Keyword Likhenge Ye Kia Kar Raha Ha Ke Object Ke Aander Name Ko Dekh Raha Ha Object Ki Properties Ab Variable Ke Name Ke Aander Save Ho Jayngi OK Our Phir Hum Ab Isko Console Kara Denge Name Ko !!                  
// console.log(prop) // Our Console Kara Denge Prop Ko Yani Name Ko OK!
// }

//////////////////////////////////////////////////////////////////////////////////

// Same Kaam Karraha Ha Bs Properties Ke Bajay Value Ladega Properties Ki OK!

// var User = {
//   Name: 'Mark',
//   Father_Name: 'Myers',
//   Roll_No: 1879,
//   School: 'Sylani',
//   Age: 18,
//   Number: 03333333122,
//   Gmail_ID: 'mark321@gmail.com'
// }

// for(var Value in User){ // I sme Ho Kia Raha Ha Bhai Is Ma Ek Loop Chal Raha Ha Our Us Loop Me Ek Variable Ban Raha Ha Our Us Ka Hum Name De Rahe Hain Our Phir Hum Check Kar Raha Hain Ke Object Ki Kitni Values Hain Our Kon Kon Si Hain Hum Name Denge Our Phir Hum in Ka Keyword Likhenge Ye Kia Kar Raha Ha Ke Object Ke Aander Name Ko Dekh Raha Ha Object Ki Value Ab Variable Ke Name Ke Aander Save Ho Jayngi OK Our Phir Hum Ab Isko Console Kara Denge Object Ke Name Ko Our + [] Array Braket Our IsKe Aander Hum Name Denge OK !!!                  
// console.log(User[Value]) // Our Console Kara Denge Values Ko Yani Properties Ki Values Ko OK!
// }

//////////////////////////////////////////////////////////////////////////////////

// Same Kaam Karraha Ha Bs Properties Aur Values Dono Ladega Object Ki OK!

// var User = {
//   Name: 'Mark',
//   Father_Name: 'Myers',
//   Roll_No: 1879,
//   School: 'Sylani',
//   Age: 18,
//   Number: 03333333122,
//   Gmail_ID: 'mark321@gmail.com'
// }

// for(var Properties_Value in User){ // Isme Ho Kia Raha Ha Bhai Is Ma Ek Loop Chal Raha Ha Our Us Loop Me Ek Variable Ban Raha Ha Our Us Ka Hum Name De Rahe Hain Our Phir Hum Check Kar Raha Hain Ke Object Ki Kitni Values Hain Our Kon Kon Si Hain Hum Name Denge Our Phir Hum in Ka Keyword Likhenge Ye Kia Kar Raha Ha Ke Object Ke Aander Name Ko Dekh Raha Ha Object Ki Value Ab Variable Ke Name Ke Aander Save Ho Jayngi OK Our Phir Hum Ab Isko Console Kara Denge Object Ke Name Ko Our + [] Array Braket Our IsKe Aander Hum Name Denge OK !!!                  
// console.log(Properties_Value,User[Properties_Value]) // Our Console Kara Denge Values Ko Yani Properties Ki Values Ko OK!
// }

//////////////////////////////////////////////////////////////////////////////////

// in Ka KeyWord Check Karta Ha Ka Object Ke Ander Ye Wali Property Ha Ya Nhi For Example!
// in Ka KeyWord object Ki Apni Property Our Jo Property Hum Ne Object Me Di Hain Wo Dono Property Return Karta Ha OK!

// var User = {
//   Name: 'Mark',
//   Father_Name: 'Myers',
//   Roll_No: 1879,
//   School: 'Sylani',
//   Age: 18,
//   Number: 03333333122,
//   Gmail_ID: 'mark321@gmail.com'
// }

// console.log(User)
// console.log("constructor" in User)

// Same Kaam Karega Bass Ye Khali Object Ke Aander Jo Value Hum Ne De Ha Khali Vai Value Print Karega OK For Example: !

// var User = {
//   Name: 'Mark',
//   Father_Name: 'Myers',
//   Roll_No: 1879,
//   School: 'Sylani',
//   Age: 18,
//   Number: 03333333122,
//   Gmail_ID: 'mark321@gmail.com'
// }

// console.log(User.hasOwnProperty('Age'))

///////////////////////////////////////////////////////////////////////////////////

// in Ka KeyWord Kia Karta Ha Bhai Ye As A Object ki Properties Ko Print KarWayga Object Ki Apni Bhi Property Hoti Hain Ye Wo Property Ko Bhi Print Karwayga OK!

// hasOwnPoperty Kya Karta Ha Bhai Ye As A Object ki Properties Ko Print KarWayga Jo Properties Hum Apne Object Ke Aander Denge OK! 
 
//////////////////////////////////////////////////////////////////////////////////

// Starting With Browser Control!

// window.location.href Kia Karta Ha Bhai Ye Us Website Ke link La Deta Ha Jahan Pr Hum Khara Howe We Hain OK! Agr Hamein Apne Browser Ki Location Maloom Karni Hoto Kese Karenge Yani Ke Me Abhi Kon Si Website Pe Khara Howa Wa Hon Us Ka URL Agr Mujhe Cheyen To KeSe Lenge Wo Hum window.location.href Ke Throw Lenge OK! For Example!
 
// console.log(`Live Website Href::    ${window.location.href}  !`)
// document.write(`Live Website Href:: ${window.location.href} !`)

////////////////////////////////////////////////////////////////////////////////////

// Agr Hamaroko Kisi Website Ka Domain Name Maloom Karna Ha To Kis Tarike Se Karte Hain Wo Hum Karte Hain window.location.hostname Ye Kia Karta Ha Bhai hostname Ladeta Ha Jis Website Pe Hum Khare Howe we Hain OK! Yani Ke Jis Website Ka Hum ne Domain Name Host Kia Ha Us Website Ka Ya Domain Name La Dega OK! 
 
// console.log(`Live Website Domain Name::    ${window.location.hostname}  !`)
// document.write(`Live Website Domain Name:: ${window.location.hostname} !`)

/////////////////////////////////////////////////////////////////////////////////////

// /selesh Ke Baad Jo URL Aata Ha Na Wo Kehlata Ha Path Name OK For Example Hum Jab Koi Website Kholte Hain To Home Page Aata Ha To Jab Hum Path Name Check Karenge To Wo /Selesh La Deta Ha Our Agr Hum Home Ke Page Se Contact Ke Page Pe Jate Hain To URL Change Ho Jata Ha To Jab Hum Path Name Check Karenge To Wo Home Ka Jo URL Hoga Us Ke Baad Yani Ke Slesh/ Ke Baad Contact Page Ka URL Aajay Ga Wo Jo / Ke Baad Url Aata Ha Wo Kehlata Ha Path Name OK For Example!
// Agr Hamaroko Apni Website Ka Path Name Chiyen Ho To Kese Get Karenge Wo Hum Is Tarike Se Get Karenge window.location.pathname Ye Kia Karega Bhai Ye Jo Hum Current Location Pe Khare Howe we Hain Us Ka Path Name La Dega OK For Example!
 
// console.log(`Live Website Path Name::    ${window.location.pathname}  !`)
// document.write(`Live Website Path Name:: ${window.location.pathname} !`)

/////////////////////////////////////////////////////////////////////////////////////

// window.location.hash Ye Kia Karta Ha Bhai Ye Check Karta Ha Ke Jo Location Aarahi Ha Wo String Me Ha Ya String Ke Bager Ye ye Check Karta Ha OK!
// window.location.hash Ye Kia Karta Ha Bhai Ye Jis Current Location Pe Hum Khare hoe Hain Us Me Koi Chezz Set Karwani Ho To Wo Hum Window.location.hash Ke Throw Set Karwate Hain OK! For Example!
// window.location.hash Ye Kia Karta Ha Bhai hum Jis Website Pe Khare Howe We Hain Na Wo Us Website Ke Href Me Jata Ha Our Check Karta Ha Ke Is Me Koi Id Ha Ya Nhi Agr Hogi To Wo Id Name La Deta Ha Our Agr Nhi Hogy To Wo Khali ""String La Deta Ha OK!
// Check By Google Console This Example!

// console.log(`Live Website Hash Set Value::    ${window.location.hash}  !`)
// document.write(`Live Website Hash Set Value:: ${window.location.hash} !`)

////////////////////////////////////////////////////////////////////////////////////

// Agr Hamaroko Koi Href Set Karwana Hoto Kis Tarike Se Set Karwayenge For Example!

// var setURL = window.location.href = "https://assignment-stop-watch-e569a.web.app/"

///////////////////////////////////////////////////////////////////////////////////

// Isme Ho Kia Raha Ha Bhai Isme Hum Ek Variable Me Domain Name De Raha Hain Our Phir Usme https:// + Karke Us Ko Href Bana Raha Hain OK! 

// var HostURL = window.location.hostname = "jibranabduljabbar.github.io/Stop-Watch/"
// var AddURL = `https://${HostURL}`;
// window.location.href = AddURL;

//////////////////////////////////////////////////////////////////////////////////

// assign Kia Karta Ha Bhai ham Jo Link Isme Assign Karenge Ye Us Link Pe Hamein Le Jay Ga OK! For Example!

// console.log(window.location.assign("https://assignment-quiz-application.web.app"))
// document.write(window.location.assign("https://assignment-stop-watch-e569a.web.app"))

//////////////////////////////////////////////////////////////////////////////////

// console.log(window.location.assign("https://assignment-quiz-application.web.app") )

// replace Kia Karta Ha Bhai IsKe Aander Jo Hum URL Pass Karte Hain Wo Us URL Pe Hamein Le Jay Ga Magr Jab Hum Back Jaynga To Ye Back Wale URL Ko Yani Ke Jis Url Se Ye Gaya Ha Us URL Ko Replace Kardega Yani Ke Remove Kardega OK For Example!
 
// console.log(window.location.href = "https://assignment-quiz-application.web.app")

//////////////////////////////////////////////////////////////////////////////////

// console.log(window.location.reload(true))

// window.location.href // returns the href (URL) of the current page
// window.location.hostname // returns the domain name of the web host
// window.location.pathname // returns the path and filename of the current page
// window.location.protocol // returns the web protocol used (http: or https:)
// window.location.assign() // loads a new document

// Congratulation JavaScript Algorithms Is Complete...!